/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/v1/tasks/{task}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a job for a task (services); returns immediately, or waits up to `waitSeconds` for the result
         * @description The Idempotency-Key names the job: a retry with the same key returns the first job. An equal request with a live or succeeded job returns that job (the cache). Completion is announced by ai.job.* events; a job already finished is returned with 200.
         */
        post: operations["runTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/tasks/answer-declarant-question/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream an answer (server-sent events: text deltas, then the job with its validated output)
         * @description Runs an `answer`-mode input of `answer-declarant-question` as a job, in the request. Events: `delta` {text}, the answer's prose as the model writes it, provisional until the end; then either `final` {job}, the succeeded job, whose output replaces the deltas (an answer that failed its checks arrives as `declined: true` with no blocks), or `error` {reason}, the job failed. A caller that disconnects fails the job with reason `cancelled`. A `: ping` comment is sent every 15 s. The Idempotency-Key names the job like the task endpoint's: a finished key returns its `final` (or `error`) only; an equal request with a succeeded job is served from it as one `delta` and its `final`.
         */
        post: operations["streamAnswerDeclarantQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job state and validated output (caller service only, for the tenant it acts for) */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/jobs/{jobId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Record or update a reviewer's rating of a job's output (caller service only)
         * @description One rating per reviewer per block of the output (`block`; null for the output as a whole): a second rating by the same reviewer of the same block replaces the first. Each rating announces ai.feedback.recorded.v1 (no note, no reviewer).
         */
        put: operations["recordFeedback"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Classification gate per tenant with explicit rules, and the default for every other pair */
        get: operations["listGatePolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/policies/{tenant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Allow or block provider classes per data class, all or none (audited with the approval reference)
         * @description The rules apply in one transaction: every rule is stored, or none is. Each rule gets its own audit record and `ai.policy.changed.v1` event, all with the approval reference.
         */
        put: operations["setGatePolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Effective routing table (task to provider, model and parameters), with tenant overrides */
        get: operations["getRouting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/routing/{task}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Route a task's calls for every tenant without its own route (audited)
         * @description The next job of the task follows it. Audited with the approval reference and announced by `ai.policy.changed.v1` (action `ai.route.changed`).
         */
        put: operations["setDefaultRoute"];
        post?: never;
        /** Remove a task's default route, back to the configured provider and model (audited) */
        delete: operations["removeDefaultRoute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/tenants/{tenant}/routing/{task}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Route a task's calls for one tenant, over the default route (audited)
         * @description The next job of the task for the tenant follows it. Audited with the approval reference and announced by `ai.policy.changed.v1` (action `ai.route.changed`).
         */
        put: operations["setTenantRoute"];
        post?: never;
        /** Remove a tenant's route of a task, back to the default route (audited) */
        delete: operations["removeTenantRoute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This month's budget and usage of every tenant with a budget or a job this month, and the default budget of the others */
        get: operations["listTenantUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/tenants/{tenant}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget, tokens and cost this month, blocked and failed counts */
        get: operations["getTenantUsage"];
        /** Set the monthly token budget and per-minute limit (audited) */
        put: operations["setTenantBudget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/tenants/{tenant}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether AI assistance is enabled for a tenant and with which provider class (review proxies it for the Commission status line)
         * @description Derived from the tenant's routes and its classification gate (explicit rules, else the default): the provider classes the tenant's Commission tasks are routed to, and the data classes every one of them may process. EACC-only tasks such as narrate-compliance-report are excluded.
         */
        get: operations["getTenantAiStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TaskName: "summarize-declaration" | "explain-flags" | "draft-clarification" | "narrate-compliance-report" | "answer-declarant-question" | "extract-document";
        /** @enum {string} */
        DataClass: "synthetic" | "restricted" | "highly-confidential";
        /** @enum {string} */
        ProviderClass: "external" | "self-hosted";
        /** @enum {string} */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "blocked";
        /**
         * @description Set when failed or blocked
         * @enum {string}
         */
        JobReason: "policy" | "budget" | "validation" | "refused" | "provider" | "provider-unavailable" | "timeout" | "cancelled" | "document-unavailable" | "document-unreadable";
        TaskRequest: {
            dataClass: components["schemas"]["DataClass"];
            /** @description Owning record, e.g. review-case:<uuid>; appears in audit and events */
            subjectRef: string;
            /**
             * @description Pin a prompt version; null uses the current one
             * @default null
             */
            promptVersion: number | null;
            /** @default 0 */
            waitSeconds: number;
            /** @description The task's input; its `kind` is the task name */
            input: components["schemas"]["SummarizeDeclarationInput"] | components["schemas"]["ExplainFlagsInput"] | components["schemas"]["DraftClarificationInput"] | components["schemas"]["NarrateComplianceReportInput"] | components["schemas"]["AnswerDeclarantQuestionInput"] | components["schemas"]["ExtractDocumentInput"];
        };
        Job: {
            /** Format: uuid */
            id: string;
            task: components["schemas"]["TaskName"];
            tenant: string;
            subjectRef: string;
            status: components["schemas"]["JobStatus"];
            reason: components["schemas"]["JobReason"] | null;
            promptVersion: number;
            provider: string | null;
            model: string | null;
            inputHash: string;
            outputHash: string | null;
            usage: {
                tokensIn: number;
                tokensOut: number;
                /** @description Estimated cost in micro US dollars (USD 1 = 1,000,000) at provider list price */
                costMicros: number;
                latencyMs: number;
            };
            /** @description The task's output; null until the job succeeded, or once purged */
            output: components["schemas"]["SummarizeDeclarationOutput"] | components["schemas"]["ExplainFlagsOutput"] | components["schemas"]["DraftClarificationOutput"] | components["schemas"]["NarrateComplianceReportOutput"] | components["schemas"]["AnswerDeclarantQuestionOutput"] | components["schemas"]["ExtractDocumentOutput"] | null;
            /** Format: date-time */
            createdAt: string;
            finishedAt: string | null;
        };
        /** @description Present on every output */
        AiLabel: {
            /** @constant */
            aiAssisted: true;
            task: components["schemas"]["TaskName"];
            promptVersion: number;
            provider: string;
            model: string;
            /** Format: date-time */
            generatedAt: string;
            /** @description Fixed text per task and language: for the reviewer tasks, indicators, not findings, a named reviewer decides; for a declarant's answers, not legal advice */
            disclaimer: string;
        };
        SourceRef: {
            sectionKey: string | null;
            personKey: string | null;
            itemId: string | null;
            /** @description JSON pointer into the declaration.v1 document */
            fieldPath: string | null;
        };
        FlagInput: {
            /** Format: uuid */
            id: string;
            ruleId: string;
            severity: string;
            title: string;
            indicator: string;
            evidence: {
                [key: string]: unknown;
            };
            itemRefs: components["schemas"]["SourceRef"][];
        };
        ChangeInput: {
            /** @enum {string} */
            kind: "acquired" | "disposed" | "value-changed" | "unchanged" | "corrected";
            personKey: string;
            sectionKey: string;
            itemId: string | null;
            percent: number | null;
        };
        RegistryStatusInput: {
            system: string;
            status: string;
        };
        SummarizeDeclarationInput: {
            /** @constant */
            kind: "summarize-declaration";
            /** @description declaration.v1 document. The gateway replaces personal identifiers with tokens before any provider call and restores them in the output */
            document: {
                [key: string]: unknown;
            };
            previousDocument: {
                [key: string]: unknown;
            } | null;
            changes: components["schemas"]["ChangeInput"][];
            flags: components["schemas"]["FlagInput"][];
            registryStatuses: components["schemas"]["RegistryStatusInput"][];
            /** @enum {string} */
            language: "en" | "sw";
        };
        SummarizeDeclarationOutput: {
            label: components["schemas"]["AiLabel"];
            overview: string;
            changesSincePrevious: {
                text: string;
                refs: components["schemas"]["SourceRef"][];
            }[];
            sections: {
                sectionKey: string;
                text: string;
                refs: components["schemas"]["SourceRef"][];
            }[];
            worthAttention: {
                text: string;
                flagIds: string[];
            }[];
        };
        ExplainFlagsInput: {
            /** @constant */
            kind: "explain-flags";
            flags: components["schemas"]["FlagInput"][];
            /** @description Minimal context for referenced items (type, description, values); personal identifiers are replaced with tokens before any provider call */
            itemContext: {
                ref: components["schemas"]["SourceRef"];
                context: {
                    [key: string]: unknown;
                };
            }[];
            /** @enum {string} */
            language: "en" | "sw";
        };
        ExplainFlagsOutput: {
            label: components["schemas"]["AiLabel"];
            explanations: {
                /** Format: uuid */
                flagId: string;
                meaning: string;
                whatToCheck: string[];
                typicalResolution: string;
                refs: components["schemas"]["SourceRef"][];
            }[];
        };
        DraftClarificationInput: {
            /** @constant */
            kind: "draft-clarification";
            commissionName: string;
            /** @enum {string} */
            language: "en" | "sw";
            selections: {
                ref: components["schemas"]["SourceRef"];
                flag: components["schemas"]["FlagInput"] | null;
                itemContext: {
                    [key: string]: unknown;
                };
                /** @description Reviewer's choice if set; the task proposes one otherwise */
                requirement: ("provide-omitted" | "explain-discrepancy" | "correct") | null;
            }[];
        };
        DraftClarificationOutput: {
            label: components["schemas"]["AiLabel"];
            opening: string | null;
            items: {
                ref: components["schemas"]["SourceRef"];
                /** @enum {string} */
                requirement: "provide-omitted" | "explain-discrepancy" | "correct";
                text: string;
            }[];
        };
        /** @description Aggregate keys name each figure: `national.<name>` for totals and rates, `commission.<code>.<name>` for a Commission row, and the same prefixed `fy<fy>.` for a prior year (`fy2025.national.filed`). Aggregates only, no person: callers send data class `restricted` */
        NarrateComplianceReportInput: {
            /** @constant */
            kind: "narrate-compliance-report";
            /** @description Financial year, by the calendar year it ends in */
            fy: number;
            /** @description National counts */
            totals: {
                [key: string]: number | null;
            };
            /** @description National rates, as fractions (0.164 is 16.4%) */
            rates: {
                [key: string]: number | null;
            };
            /** @description One row per Commission: code, name and its figures, rates as fractions */
            commissionTable: {
                /** @description Commission slug; names the row in aggregate keys */
                code: string;
                /** @description A public body, not a person: outside the name fields minimisation tokenises */
                commissionName: string;
                figures: {
                    [key: string]: number | null;
                };
            }[];
            priorYears: {
                /** @description Financial year, by the calendar year it ends in */
                fy: number;
                /** @description National counts */
                totals: {
                    [key: string]: number | null;
                };
                /** @description National rates, as fractions (0.164 is 16.4%) */
                rates: {
                    [key: string]: number | null;
                };
                /** @description One row per Commission: code, name and its figures, rates as fractions */
                commissionTable: {
                    /** @description Commission slug; names the row in aggregate keys */
                    code: string;
                    /** @description A public body, not a person: outside the name fields minimisation tokenises */
                    commissionName: string;
                    figures: {
                        [key: string]: number | null;
                    };
                }[];
            }[];
            candidates: {
                id: string;
                /** @enum {string} */
                kind: "rate-change" | "threshold-breach" | "chronic-late-reporting" | "clarification-ratio-outlier" | "size-band-outlier" | "non-reporting";
                /** @description Commission slug, entity type, or `national` */
                subject: string;
                values: {
                    [key: string]: number | string | null;
                };
                aggregateKeys: string[];
            }[];
            /**
             * @description `findings` and `all` need at least one candidate: a finding narrates a computed pattern, so with none no draft could pass validation
             * @enum {string}
             */
            section: "overview" | "findings" | "recommendations" | "all";
            /** @enum {string} */
            language: "en";
        };
        NarrateComplianceReportOutput: {
            label: components["schemas"]["AiLabel"];
            /** @description The job fails with reason `validation` unless every number in the text is in the input (separators stripped; a percentage is a rate ×100 rounded half up to the places written, at most two; years only as input FYs), every aggregate ref and candidate id is in the input, every finding narrates a candidate, and the paragraphs cover exactly the sections asked for (overview at most 3, findings 12, recommendations 6) */
            paragraphs: {
                /** @enum {string} */
                section: "overview" | "findings" | "recommendations";
                text: string;
                aggregateRefs: string[];
                candidateIds: string[];
            }[];
        };
        AnswerDeclarantQuestionInput: {
            /** @constant */
            kind: "answer-declarant-question";
            /**
             * @description `answer` streams an answer to the question (stream endpoint only); `hints` writes one hint per residual (job endpoint only)
             * @enum {string}
             */
            mode: "answer" | "hints";
            /** @enum {string} */
            language: "en" | "sw";
            /** @description The declarant's question; null in hints mode */
            question: string | null;
            /** @description Never contains amounts, names, identifiers or descriptions */
            context: {
                /** @description The type of the declaration being filled (declarations.yaml) */
                declarationType: ("initial" | "biennial" | "final") | null;
                statementDate: string | null;
                householdCounts: {
                    spouses: number;
                    children: number;
                };
                /** @description The section the declarant is on */
                sectionKey: string | null;
                /** @description What the completeness check still reports: where, and by which rule */
                residuals: {
                    /** @description bio, household, other, or statement:<personKey> (declarations.yaml) */
                    sectionKey: string;
                    /** @description The completeness rule or schema keyword that reports it, e.g. nil-or-items-required, minLength */
                    ruleId: string;
                    /** @description JSON pointer within the section, field names and indexes: /assets/1/value */
                    fieldPath: string;
                }[];
            };
            /** @description Retrieved corpus passages; an answer may cite only these */
            passages: {
                id: string;
                citation: string;
                text: string;
            }[];
            /** @description Earlier turns, oldest first, to resolve follow-up questions */
            history: {
                /** @enum {string} */
                role: "user" | "assistant";
                text: string;
            }[];
        };
        AnswerDeclarantQuestionOutput: {
            label: components["schemas"]["AiLabel"];
            /** @description The passages do not answer the question; also set when a streamed answer fails its checks, which then has no blocks */
            declined: boolean;
            blocks: {
                text: string;
                /** @description Passages the block rests on, all from the input; at least one in answer mode */
                passageIds: string[];
                /** @description Where in the declaration the block is about; in hints mode, its residual */
                sectionLink: {
                    /** @description bio, household, other, or statement:<personKey> (declarations.yaml) */
                    sectionKey: string;
                    fieldPath: string | null;
                } | null;
            }[];
            followUps: string[];
        };
        ExtractDocumentInput: {
            /** @constant */
            kind: "extract-document";
            /** @enum {string} */
            documentKindHint: "title-deed" | "logbook" | "payslip" | "bank-letter" | "share-certificate" | "other";
            /** @description The declaration.v1 statement item the fields must fit: its section and Second Schedule item type */
            target: {
                /** @constant */
                section: "assets";
                /** @enum {string} */
                itemType: "land" | "building" | "vehicle" | "securities" | "shareholding" | "bank-account" | "cash" | "receivable" | "other";
            } | {
                /** @constant */
                section: "income";
                /** @enum {string} */
                itemType: "salary-emoluments" | "allowances" | "business" | "rent" | "dividends-interest" | "pension" | "farming" | "consultancy" | "other";
            } | {
                /** @constant */
                section: "liabilities";
                /** @enum {string} */
                itemType: "mortgage" | "loan" | "guarantee" | "other";
            };
            attachment: {
                /**
                 * Format: uri
                 * @description Short-lived internal URL from the documents service; the gateway fetches it, and never sends it to a provider
                 */
                downloadUrl: string;
                /** @enum {string} */
                contentType: "application/pdf" | "image/jpeg" | "image/png" | "image/webp";
                /** @description The file must hash to it; with the rest of the input, the cache key */
                sha256: string;
            };
            /** @enum {string} */
            language: "en" | "sw";
        };
        ExtractDocumentOutput: {
            label: components["schemas"]["AiLabel"];
            /** @enum {string} */
            detectedKind: "title-deed" | "logbook" | "payslip" | "bank-letter" | "share-certificate" | "other";
            fields: {
                /** @description Field path within the target item type */
                name: string;
                /** @description Typed as declaration.v1 types the field: text, a number or a boolean */
                value: string | number | boolean;
                /** @description How sure the reading is: 1 printed and clear, below 0.5 a guess */
                confidence: number;
                /** @description The page the value is on; null when it is on none (worked out) */
                page: number | null;
            }[];
            /** @description What the declarant should know about the reading (an unreadable page, a document that is not the item's), in the request's language */
            warnings: string[];
        };
        FeedbackInput: {
            /** @description The reviewer rating the output, as the calling service knows them (token `sub`) */
            reviewerSubject: string;
            /** @description The block rated: a summary's `overview`, `changes`, `sections` or `worth-attention`, or an explanation's `flag:<flagId>`. Null or left out: the output as a whole */
            block?: string | null;
            /** @enum {string} */
            rating: "helpful" | "not-helpful";
            reason: ("inaccurate" | "missed-something" | "unclear" | "too-long" | "other") | null;
            note: string | null;
        };
        Feedback: {
            /** Format: uuid */
            jobId: string;
            /** @description The reviewer rating the output, as the calling service knows them (token `sub`) */
            reviewerSubject: string;
            /** @description The block rated; null for the output as a whole */
            block: string | null;
            /** @enum {string} */
            rating: "helpful" | "not-helpful";
            reason: ("inaccurate" | "missed-something" | "unclear" | "too-long" | "other") | null;
            note: string | null;
            /** Format: date-time */
            at: string;
        };
        TenantAiStatus: {
            tenant: string;
            /** @description Some data class may be sent to the tenant's routed provider class */
            enabled: boolean;
            /** @description The provider class of the tenant's reviewer task routes; `external` when they are on more than one. Null when no route names a provider this gateway can reach */
            providerClass: components["schemas"]["ProviderClass"] | null;
            /** @description The provider the tenant's reviewer task routes name, of `providerClass` (the first by task order when they name several). Null when `providerClass` is */
            provider: string | null;
            /** @description Data classes every routed provider class may process, in DataClass order */
            dataClasses: components["schemas"]["DataClass"][];
        };
        GateRuleInput: {
            dataClass: components["schemas"]["DataClass"];
            providerClass: components["schemas"]["ProviderClass"];
            allowed: boolean;
            /** @description The tasks the rule is for; null for every task, which a rule for some tasks only needs to be widened. Left out: every task for a new rule; refused for a rule that names tasks */
            tasks?: components["schemas"]["TaskName"][] | null;
        };
        GateCell: {
            dataClass: components["schemas"]["DataClass"];
            providerClass: components["schemas"]["ProviderClass"];
            allowed: boolean;
        };
        GatePolicyInput: {
            /** @description At most one rule per data class and provider class */
            rules: components["schemas"]["GateRuleInput"][];
            /** @description The decision the change rests on, e.g. an EACC approval number */
            approvalRef: string;
        };
        /** @description An explicit rule of a tenant's gate, with who decided it and on which approval */
        GateRule: {
            dataClass: components["schemas"]["DataClass"];
            providerClass: components["schemas"]["ProviderClass"];
            allowed: boolean;
            /** @description The tasks the rule is for; null for every task. Any other task follows the gate's default for the pair */
            tasks: components["schemas"]["TaskName"][] | null;
            approvalRef: string;
            /** @description `sub` of the platform admin who made the change */
            changedBy: string;
            /** @description Their display name at the time; null when unknown */
            changedByName: string | null;
            /** Format: date-time */
            changedAt: string;
        };
        TenantPolicy: {
            tenant: string;
            /** @description Explicit rules, allowing or blocking, in DataClass then ProviderClass order. A pair without one follows `GatePolicyList.defaults` */
            rules: components["schemas"]["GateRule"][];
        };
        GatePolicyList: {
            /** @description The gate of every (data class, provider class) pair a tenant has no rule for: self-hosted providers may see every data class, external providers none, so a new tenant sends nothing outside the platform until a platform admin records an approved rule (the demo tenant's synthetic rule is seeded that way) */
            defaults: components["schemas"]["GateCell"][];
            /** @description Tenants with at least one explicit rule, by tenant */
            tenants: components["schemas"]["TenantPolicy"][];
        };
        /** @description Call parameters; an unset one falls back to the task's own */
        RouteParams: {
            maxOutputTokens?: number;
            /** @enum {string} */
            effort?: "low" | "medium" | "high";
            /** @description Longest one provider call may take */
            timeoutMs?: number;
        };
        Route: {
            /** @description null is the default route */
            tenant: string | null;
            task: components["schemas"]["TaskName"];
            provider: string;
            /** @description The provider's class, which the gate decides on; null when this gateway cannot reach the provider (its jobs fail `provider-unavailable`) */
            providerClass: components["schemas"]["ProviderClass"] | null;
            model: string;
            params: components["schemas"]["RouteParams"];
            /** @description True for a task with no default route, which follows the gateway's configured provider and model; false for a route set through this API */
            configured: boolean;
        };
        /** @description A task's route: provider, model and call parameters */
        RouteInput: {
            /** @description A provider this gateway is configured to reach (`Route.provider` names them) */
            provider: string;
            model: string;
            /** @default {} */
            params: components["schemas"]["RouteParams"];
            /** @description The decision the change rests on, e.g. an EACC approval number */
            approvalRef: string;
        };
        BudgetInput: {
            /** @description Tokens (in and out) per calendar month, Africa/Nairobi */
            monthlyTokens: number;
            /** @description Jobs created per minute */
            perMinute: number;
        };
        TenantUsage: {
            tenant: string;
            /** @description Calendar month, Africa/Nairobi */
            month: string;
            monthlyTokens: number;
            perMinute: number;
            tokensUsed: number;
            /** @description Estimated cost in micro US dollars (USD 1 = 1,000,000) at provider list price */
            costMicros: number;
            jobs: number;
            blocked: number;
            failed: number;
        };
        UsageList: {
            /** @description Calendar month, Africa/Nairobi */
            month: string;
            defaults: components["schemas"]["BudgetInput"];
            /** @description Tenants with a budget of their own or a job this month, by tenant */
            tenants: components["schemas"]["TenantUsage"][];
        };
        ProblemDetails: {
            type: string;
            title: string;
            status: number;
            /**
             * @description Machine-readable cause, from the platform registry; clients map it to copy and never show `title` or `detail`
             * @enum {string}
             */
            code?: "database-unavailable" | "rate-limit-exceeded" | "no-match" | "already-onboarded" | "no-roster" | "otp-invalid" | "otp-expired" | "resend-cooldown" | "otp-send-failed" | "wrong-step" | "session-expired" | "iprs-unavailable" | "identity-unavailable" | "email-in-use" | "identity-mismatch" | "step-up-required" | "incomplete" | "before-statement-date" | "amendment-window-closed" | "not-a-draft" | "not-submitted" | "obligation-cancelled" | "acknowledgement-issued" | "acknowledgement-in-progress" | "consent-required" | "no-id" | "not-new" | "no-applicant-record" | "request-decided" | "request-closed" | "officer-resolved" | "not-under-decision" | "not-pending-verification" | "lea-account-inactive" | "declarant-notified" | "representations-closed" | "download-window-closed" | "scope-exceeds-request" | "grounds-required";
            detail?: string;
            instance?: string;
            /** @description Field-level errors; `path` is the dotted request field */
            errors?: {
                path: string;
                message: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    runTask: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant the calling service acts for; the resource must belong to it */
                "X-Acting-Tenant": string;
                /** @description Client-generated UUID, unique per logical request; reuse on retry */
                "Idempotency-Key": string;
            };
            path: {
                task: components["schemas"]["TaskName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRequest"];
            };
        };
        responses: {
            /** @description The job has finished (within the wait window, or before) */
            200: {
                headers: {
                    /** @description `true` when the key named an existing job, which is returned as it is now */
                    "Idempotent-Replayed"?: "true";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Queued or running; completion announced by ai.job.* events */
            202: {
                headers: {
                    /** @description `true` when the key named an existing job, which is returned as it is now */
                    "Idempotent-Replayed"?: "true";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Request failed validation (`answer-declarant-question` takes data class `synthetic` only), an input the task streams (`task-streamed`: `answer`-mode `answer-declarant-question`, sent to its stream endpoint), Idempotency-Key missing or not a UUID, or X-Acting-Tenant missing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Requires a service token with scope ai:internal */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unknown task */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Idempotency-Key reused with a different request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Tenant's per-minute limit reached (code `rate-limit-exceeded`); no job was created. `retryAfterSeconds` and Retry-After say when to try again */
            429: {
                headers: {
                    /** @description Seconds until the next request would be allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    streamAnswerDeclarantQuestion: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant the calling service acts for; the resource must belong to it */
                "X-Acting-Tenant": string;
                /** @description Client-generated UUID, unique per logical request; reuse on retry */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRequest"];
            };
        };
        responses: {
            /** @description SSE stream: `delta` {text}, then `final` {job: Job} or `error` {reason: JobReason} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Request failed validation (data class `synthetic` only), a `hints` input (`task-not-streamed`, run it as a job), Idempotency-Key missing or not a UUID, or X-Acting-Tenant missing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The classification gate refused it (`task-blocked`, `reason: policy`); the blocked job is recorded */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The Idempotency-Key, or an equal request, is streaming now (`job-in-progress`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Idempotency-Key reused with a different request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Tenant's per-minute limit reached (code `rate-limit-exceeded`, no job), or its monthly budget spent (`task-blocked`, `reason: budget`) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No provider reachable for the route (`task-blocked`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant the calling service acts for; the resource must belong to it */
                "X-Acting-Tenant": string;
            };
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description The id is not a UUID, or X-Acting-Tenant is missing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Requires a service token with scope ai:internal */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found, another caller's job, or another tenant's */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    recordFeedback: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant the calling service acts for; the resource must belong to it */
                "X-Acting-Tenant": string;
            };
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackInput"];
            };
        };
        responses: {
            /** @description Recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            /** @description Request failed validation, or X-Acting-Tenant is missing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Requires a service token with scope ai:internal */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No succeeded job with this id of the caller, for the tenant it acts for */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listGatePolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatePolicyList"];
                };
            };
            /** @description Caller is not a platform admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    setGatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatePolicyInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantPolicy"];
                };
            };
            /** @description Request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Caller is not a platform admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getRouting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Routing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"][];
                };
            };
            /** @description Caller is not a platform admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    setDefaultRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task: "summarize-declaration" | "explain-flags" | "draft-clarification" | "narrate-compliance-report" | "answer-declarant-question" | "extract-document";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Request failed validation, or the provider is not one this gateway reaches */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Caller is not a platform admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    removeDefaultRoute: {
        parameters: {
            query: {
                /** @description The decision the change rests on, e.g. an EACC approval number */
                approvalRef: string;
            };
            header?: never;
            path: {
                task: "summarize-declaration" | "explain-flags" | "draft-clarification" | "narrate-compliance-report" | "answer-declarant-question" | "extract-document";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Caller is not a platform admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The task has no default route */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    setTenantRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
                task: "summarize-declaration" | "explain-flags" | "draft-clarification" | "narrate-compliance-report" | "answer-declarant-question" | "extract-document";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Request failed validation, the task is one only EACC calls (it has only a default route), or the provider is not one this gateway reaches */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Caller is not a platform admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    removeTenantRoute: {
        parameters: {
            query: {
                /** @description The decision the change rests on, e.g. an EACC approval number */
                approvalRef: string;
            };
            header?: never;
            path: {
                tenant: string;
                task: "summarize-declaration" | "explain-flags" | "draft-clarification" | "narrate-compliance-report" | "answer-declarant-question" | "extract-document";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Caller is not a platform admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The tenant has no route of its own for the task */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listTenantUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageList"];
                };
            };
            /** @description Caller is not a platform admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTenantUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUsage"];
                };
            };
            /** @description Request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Caller is not a platform admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    setTenantBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUsage"];
                };
            };
            /** @description Request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Caller is not a platform admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTenantAiStatus: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant the calling service acts for; the resource must belong to it */
                "X-Acting-Tenant": string;
            };
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantAiStatus"];
                };
            };
            /** @description Request failed validation, or X-Acting-Tenant is missing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Requires a service token with scope ai:internal */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The tenant is not the one the caller acts for */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
