/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/v1/tasks/{task}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task: components["parameters"]["Task"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a job for a task (services); returns immediately, or waits up to `waitSeconds` for the result */
        post: operations["runTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/tasks/answer-declarant-question/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream an answer (server-sent events: text deltas, then one final structured frame that is validated like a job output) */
        post: operations["streamAnswerDeclarantQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** Job state and validated output (caller service only) */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/jobs/{jobId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Record or update a reviewer's rating of a job's output (caller service only)
         * @description One rating per reviewer per job: a second rating by the same reviewer replaces the first. Only a succeeded job of the caller has an output to rate. Each rating announces `ai.feedback.recorded.v1` (no note, no reviewer).
         */
        put: operations["recordFeedback"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/tenants/{tenant}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        /**
         * Whether AI assistance is enabled for a tenant and with which provider class (services with the `ai` scope; review proxies it for the Commission status line)
         * @description Derived from the tenant's routes and its classification gate (explicit rules, else the
         *     default): the provider classes the tenant's tasks are routed to, and the data classes
         *     every one of them may process. With routes on more than one provider class,
         *     `providerClass` is `external`.
         */
        get: operations["getTenantAiStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Classification gate per tenant with explicit rules, and the default for every other pair (platform-admin) */
        get: operations["listGatePolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/policies/{tenant}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Allow or block provider classes per data class, all or none (platform-admin; audited with approval reference)
         * @description The rules apply in one transaction: every rule is stored, or none is. Each rule gets
         *     its own audit record and `ai.policy.changed.v1` event, all with the approval reference.
         */
        put: operations["setGatePolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Effective routing table (task → provider, model, parameters) per tenant override (platform-admin) */
        get: operations["getRouting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This month's budget and usage of every tenant with a budget or a job this month, and the default budget of the others (platform-admin) */
        get: operations["listTenantUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/tenants/{tenant}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        /** Budget, tokens and cost this month, blocked and failed counts (platform-admin) */
        get: operations["getTenantUsage"];
        /** Set the monthly token budget and per-minute limit (platform-admin; audited) */
        put: operations["setTenantBudget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TaskName: "summarize-declaration" | "explain-flags" | "draft-clarification" | "extract-document" | "answer-declarant-question" | "narrate-compliance-report";
        /** @enum {string} */
        DataClass: "synthetic" | "restricted" | "highly-confidential";
        /** @enum {string} */
        ProviderClass: "external" | "self-hosted";
        /** @enum {string} */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "blocked";
        /**
         * @description Set when failed or blocked
         * @enum {string}
         */
        JobReason: "policy" | "budget" | "validation" | "refused" | "provider" | "provider-unavailable" | "timeout";
        TaskRequest: {
            tenant: string;
            dataClass: components["schemas"]["DataClass"];
            /** @description Owning record, e.g. review-case:<uuid>; appears in audit and events */
            subjectRef: string;
            /** @description Pin a prompt version; null uses the current one */
            promptVersion?: number | null;
            /** @default 0 */
            waitSeconds: number;
            input: components["schemas"]["SummarizeDeclarationInput"] | components["schemas"]["ExplainFlagsInput"] | components["schemas"]["DraftClarificationInput"] | components["schemas"]["ExtractDocumentInput"] | components["schemas"]["AnswerDeclarantQuestionInput"] | components["schemas"]["NarrateComplianceReportInput"];
        };
        Job: {
            /** Format: uuid */
            id: string;
            task: components["schemas"]["TaskName"];
            tenant: string;
            subjectRef: string;
            status: components["schemas"]["JobStatus"];
            reason: components["schemas"]["JobReason"] | null;
            promptVersion: number;
            provider: string | null;
            model: string | null;
            inputHash: string;
            outputHash: string | null;
            usage: {
                tokensIn: number;
                tokensOut: number;
                /** @description Estimated cost in micro US dollars at provider list price */
                costMicros: number;
                latencyMs: number;
            };
            output: components["schemas"]["SummarizeDeclarationOutput"] | components["schemas"]["ExplainFlagsOutput"] | components["schemas"]["DraftClarificationOutput"] | components["schemas"]["ExtractDocumentOutput"] | components["schemas"]["AnswerDeclarantQuestionOutput"] | components["schemas"]["NarrateComplianceReportOutput"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt: string | null;
        };
        /** @description Present on every output */
        AiLabel: {
            /** @constant */
            aiAssisted: true;
            task: components["schemas"]["TaskName"];
            promptVersion: number;
            provider: string;
            model: string;
            /** Format: date-time */
            generatedAt: string;
            /** @description Fixed text: indicators, not findings; a named officer decides */
            disclaimer: string;
        };
        SourceRef: {
            sectionKey: string | null;
            personKey: string | null;
            /** Format: uuid */
            itemId: string | null;
            /** @description JSON pointer into the declaration.v1 document */
            fieldPath: string | null;
        };
        FlagInput: {
            /** Format: uuid */
            id: string;
            ruleId: string;
            severity: string;
            title: string;
            indicator: string;
            evidence: {
                [key: string]: unknown;
            };
            itemRefs: components["schemas"]["SourceRef"][];
        };
        ChangeInput: {
            /** @enum {string} */
            kind: "acquired" | "disposed" | "value-changed" | "unchanged" | "corrected";
            personKey: string;
            sectionKey: string;
            /** Format: uuid */
            itemId: string | null;
            percent: number | null;
        };
        RegistryStatusInput: {
            system: string;
            status: string;
        };
        SummarizeDeclarationInput: {
            /** @constant */
            kind: "summarize-declaration";
            /** @description declaration.v1 document (minimised by the gateway before any provider call) */
            document: {
                [key: string]: unknown;
            };
            previousDocument: {
                [key: string]: unknown;
            } | null;
            changes: components["schemas"]["ChangeInput"][];
            flags: components["schemas"]["FlagInput"][];
            registryStatuses: components["schemas"]["RegistryStatusInput"][];
            /** @enum {string} */
            language: "en" | "sw";
        };
        SummarizeDeclarationOutput: {
            label: components["schemas"]["AiLabel"];
            overview: string;
            changesSincePrevious: {
                text: string;
                refs: components["schemas"]["SourceRef"][];
            }[];
            sections: {
                sectionKey: string;
                text: string;
                refs: components["schemas"]["SourceRef"][];
            }[];
            worthAttention: {
                text: string;
                flagIds: string[];
            }[];
        };
        ExplainFlagsInput: {
            /** @constant */
            kind: "explain-flags";
            flags: components["schemas"]["FlagInput"][];
            /** @description Minimal context for referenced items (type, description, values); minimised by the gateway */
            itemContext: {
                ref: components["schemas"]["SourceRef"];
                context: {
                    [key: string]: unknown;
                };
            }[];
            /** @enum {string} */
            language: "en" | "sw";
        };
        ExplainFlagsOutput: {
            label: components["schemas"]["AiLabel"];
            explanations: {
                /** Format: uuid */
                flagId: string;
                meaning: string;
                whatToCheck: string[];
                typicalResolution: string;
                refs: components["schemas"]["SourceRef"][];
            }[];
        };
        DraftClarificationInput: {
            /** @constant */
            kind: "draft-clarification";
            commissionName: string;
            /** @enum {string} */
            language: "en" | "sw";
            selections: {
                ref: components["schemas"]["SourceRef"];
                flag: components["schemas"]["FlagInput"] | null;
                itemContext: {
                    [key: string]: unknown;
                };
                /**
                 * @description Reviewer's choice if set; the task proposes one otherwise
                 * @enum {string|null}
                 */
                requirement: "provide-omitted" | "explain-discrepancy" | "correct" | null;
            }[];
        };
        DraftClarificationOutput: {
            label: components["schemas"]["AiLabel"];
            opening: string | null;
            items: {
                ref: components["schemas"]["SourceRef"];
                /** @enum {string} */
                requirement: "provide-omitted" | "explain-discrepancy" | "correct";
                text: string;
            }[];
        };
        ExtractDocumentInput: {
            /** @constant */
            kind: "extract-document";
            /** @enum {string} */
            documentKindHint: "title-deed" | "logbook" | "payslip" | "bank-letter" | "share-certificate" | "other";
            /** @description Second Schedule item type from declaration.v1 the fields must fit */
            targetItemType: string;
            attachment: {
                /**
                 * Format: uri
                 * @description Short-lived internal URL from the documents service
                 */
                downloadUrl: string;
                contentType: string;
                sha256: string;
            };
            /** @enum {string} */
            language: "en" | "sw";
        };
        ExtractDocumentOutput: {
            label: components["schemas"]["AiLabel"];
            detectedKind: string;
            fields: {
                /** @description Field path within the target item type */
                name: string;
                /** @description Typed per field; strings, numbers or dates */
                value: unknown;
                confidence: number;
                page: number | null;
            }[];
            warnings: string[];
        };
        AnswerDeclarantQuestionInput: {
            /** @constant */
            kind: "answer-declarant-question";
            /** @enum {string} */
            mode: "answer" | "hints";
            /** @enum {string} */
            language: "en" | "sw";
            /** @description null in hints mode */
            question: string | null;
            /** @description Never contains amounts, names, identifiers or descriptions */
            context: {
                declarationType: string | null;
                /** Format: date */
                statementDate: string | null;
                householdCounts: {
                    spouses: number;
                    children: number;
                };
                sectionKey: string | null;
                residuals: {
                    ruleId: string;
                    fieldPath: string;
                }[];
            };
            passages: {
                id: string;
                citation: string;
                text: string;
            }[];
            history: {
                /** @enum {string} */
                role: "user" | "assistant";
                text: string;
            }[];
        };
        AnswerDeclarantQuestionOutput: {
            label: components["schemas"]["AiLabel"];
            declined: boolean;
            blocks: {
                text: string;
                passageIds: string[];
                sectionLink: {
                    sectionKey: string;
                    fieldPath: string | null;
                } | null;
            }[];
            followUps: string[];
        };
        NarrateComplianceReportInput: {
            /** @constant */
            kind: "narrate-compliance-report";
            fy: number;
            /** @enum {string} */
            section: "overview" | "findings" | "recommendations" | "all";
            /** @enum {string} */
            language: "en";
            totals: {
                [key: string]: unknown;
            };
            commissionTable: {
                [key: string]: unknown;
            }[];
            rates: {
                [key: string]: unknown;
            };
            priorYears: {
                [key: string]: unknown;
            }[];
            candidates: {
                id: string;
                kind: string;
                subject: string;
                values: {
                    [key: string]: unknown;
                };
                aggregateKeys: string[];
            }[];
        };
        NarrateComplianceReportOutput: {
            label: components["schemas"]["AiLabel"];
            paragraphs: {
                /** @enum {string} */
                section: "overview" | "findings" | "recommendations";
                text: string;
                aggregateRefs: string[];
                candidateIds: string[];
            }[];
        };
        FeedbackInput: {
            /** @description The officer rating the output, as the calling service knows them (token `sub`) */
            reviewerSubject: string;
            /** @enum {string} */
            rating: "helpful" | "not-helpful";
            /** @enum {string|null} */
            reason: "inaccurate" | "missed-something" | "unclear" | "too-long" | "other" | null;
            note: string | null;
        };
        Feedback: components["schemas"]["FeedbackInput"] & {
            /** Format: uuid */
            jobId: string;
            /** Format: date-time */
            at: string;
        };
        TenantAiStatus: {
            tenant: string;
            /** @description Some data class may be sent to the tenant's routed provider class */
            enabled: boolean;
            /** @description null when no route names a provider this gateway can reach */
            providerClass: components["schemas"]["ProviderClass"] | null;
            /** @description Data classes the routed provider class may process, in DataClass order */
            dataClasses: components["schemas"]["DataClass"][];
        };
        GateRuleInput: {
            dataClass: components["schemas"]["DataClass"];
            providerClass: components["schemas"]["ProviderClass"];
            allowed: boolean;
        };
        GatePolicyInput: {
            /** @description At most one rule per data class and provider class */
            rules: components["schemas"]["GateRuleInput"][];
            /** @description The decision the change rests on, e.g. an EACC approval number */
            approvalRef: string;
        };
        /** @description An explicit rule of a tenant's gate, with who decided it and on which approval */
        GateRule: components["schemas"]["GateRuleInput"] & {
            approvalRef: string;
            /** @description `sub` of the platform admin who made the change */
            changedBy: string;
            /** @description Their display name at the time; null when unknown */
            changedByName: string | null;
            /** Format: date-time */
            changedAt: string;
        };
        TenantPolicy: {
            tenant: string;
            /**
             * @description Explicit rules, allowing or blocking, in DataClass then ProviderClass order. A pair
             *     without one follows `GatePolicyList.defaults`.
             */
            rules: components["schemas"]["GateRule"][];
        };
        GatePolicyList: {
            /**
             * @description The gate of every (data class, provider class) pair a tenant has no rule for:
             *     self-hosted providers may see every data class, external providers none, so a new
             *     tenant sends nothing outside the platform until a platform admin records an approved
             *     rule (the demo tenant's synthetic rule is seeded that way).
             */
            defaults: components["schemas"]["GateRuleInput"][];
            /** @description Tenants with at least one explicit rule, by tenant */
            tenants: components["schemas"]["TenantPolicy"][];
        };
        /** @description Call parameters; an unset one falls back to the task's own */
        RouteParams: {
            maxOutputTokens?: number;
            /** @enum {string} */
            effort?: "low" | "medium" | "high";
            /** @description Longest one provider call may take */
            timeoutMs?: number;
        };
        Route: {
            /** @description null is the default route */
            tenant: string | null;
            task: components["schemas"]["TaskName"];
            provider: string;
            /** @description The provider's class, which the gate decides on; null when this gateway cannot reach the provider (its jobs fail `provider-unavailable`) */
            providerClass: components["schemas"]["ProviderClass"] | null;
            model: string;
            params: components["schemas"]["RouteParams"];
        };
        BudgetInput: {
            /** @description Tokens (in and out) per calendar month, Africa/Nairobi */
            monthlyTokens: number;
            /** @description Jobs created per minute */
            perMinute: number;
        };
        TenantUsage: {
            tenant: string;
            /** @description Calendar month, Africa/Nairobi */
            month: string;
            monthlyTokens: number;
            perMinute: number;
            tokensUsed: number;
            /** @description Estimated cost in micro US dollars (USD 1 = 1,000,000) at provider list price */
            costMicros: number;
            jobs: number;
            blocked: number;
            failed: number;
        };
        UsageList: {
            /** @description Calendar month, Africa/Nairobi */
            month: string;
            /** @description The budget of a tenant without one of its own; such a tenant without jobs this month has used nothing */
            defaults: components["schemas"]["BudgetInput"];
            /** @description Tenants with a budget of their own or a job this month, by tenant */
            tenants: components["schemas"]["TenantUsage"][];
        };
        ProblemDetails: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            code?: string;
            errors?: {
                path: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Not found, or not visible to the caller */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Caller lacks the required role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request failed validation */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        Task: components["schemas"]["TaskName"];
        JobId: string;
        Tenant: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    runTask: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                task: components["parameters"]["Task"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRequest"];
            };
        };
        responses: {
            /** @description Finished within the wait window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Queued; completion announced by ai.job.* events */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            /** @description Per-tenant rate limit (jobs per minute); problem code `rate-limit-exceeded` with `retryAfterSeconds` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    streamAnswerDeclarantQuestion: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRequest"];
            };
        };
        responses: {
            /** @description SSE stream; events `delta` {text}, `final` {job}, `error` {reason} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["ValidationProblem"];
            /** @description Per-tenant rate limit (jobs per minute); problem code `rate-limit-exceeded` with `retryAfterSeconds` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    recordFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackInput"];
            };
        };
        responses: {
            /** @description Recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            /** @description No succeeded job with this id visible to the caller */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTenantAiStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantAiStatus"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["Forbidden"];
        };
    };
    listGatePolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatePolicyList"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    setGatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatePolicyInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantPolicy"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRouting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Routing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listTenantUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageList"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getTenantUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUsage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["Forbidden"];
        };
    };
    setTenantBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUsage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["Forbidden"];
        };
    };
}
