# Generated by Django 6.1.1 on 2026-09-25 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dissolved', 'Dissolved')], max_length=10)),
                ('registered_on', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='Directorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(db_index=True, max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('director', 'Director'), ('shareholder', 'Shareholder'), ('director_shareholder', 'Director and shareholder')], max_length=25)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('appointed_on', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorships', to='brs.company')),
            ],
            options={
                'ordering': ['company__registration_number', 'id_number'],
                'constraints': [models.UniqueConstraint(fields=('company', 'id_number'), name='brs_unique_person_role')],
            },
        ),
    ]
