/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/access/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The applicant's requests, latest first
         * @description Their own only. Each timeline leaves out the declarant's representations and names no actor but the applicant.
         */
        get: operations["listMyAccessRequests"];
        put?: never;
        /**
         * Submit Form K (applicant); allocates the ARQ reference and acknowledges
         * @description The request is `submitted`, or `pending-applicant-verification` while the applicant's identity is pending in the directory (a passport holder no access officer has verified yet). The acknowledgement (email and SMS, with the reference) follows from the `access.request.received.v1` event.
         */
        post: operations["submitAccessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One request with decision and package status (applicant) */
        get: operations["getMyAccessRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/requests/{requestId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw before a decision
         * @description Any status before a decision becomes `withdrawn`, recorded in the access register (`access.request.withdrawn.v1`).
         */
        post: operations["withdrawAccessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/commissions/{slug}/access/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queue of access requests with deadlines (access officer; supervisor reads)
         * @description Earliest decision deadline first. `late`: past the deadline and neither decided nor closed. Law enforcement requests join the queue with their own workspace (`kind=lea` is empty until then).
         */
        get: operations["listCommissionAccessRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/requests/{requestId}/officer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full request for the access officer (Form K, representations, register) */
        get: operations["getAccessRequestForOfficer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/requests/{requestId}/roster-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the Commission's roster for the officer a request names (access officer)
         * @description By personnel file number (its beginning) or part of the name, at most 20 records by full name. Only an `onboarded` record can be chosen: its declarant is notified.
         */
        get: operations["listRosterCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/requests/{requestId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Identify the officer on the roster, or record that they cannot be identified
         * @description A roster record: the declarant is notified next (`awaiting-representations`, with the window for representations). `rosterRecordId: null`: the request closes as `cannot-identify` (`access.request.cannot-identify.v1`, Form M decline reason `other`) and the applicant is told.
         */
        post: operations["resolveRequestedOfficer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/requests/{requestId}/verify-applicant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record manual verification of a passport applicant
         * @description The access officer of the request's Commission checked the particulars a passport applicant entered. Verified: the directory records the applicant's identity as verified, and the request goes from `pending-applicant-verification` to `submitted` (`access.request.verified.v1`). Not verified: the check is recorded and the request stays held.
         */
        post: operations["verifyApplicantIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/access-notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Requests the declarant has been notified about, with windows and outcomes
         * @description Their own only, from notification on; latest notified first.
         */
        get: operations["listMyAccessNotices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/access-notices/{requestId}/representations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create or update representations within the window
         * @description One submission per request, changed as often as needed until the window closes (`access.request.representations.v1` each time). `consent` puts the request under decision at once and closes the window.
         */
        put: operations["submitRepresentations"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/commissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Commissions an applicant can address, with the declaration years available */
        get: operations["listAccessCommissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/requests/{requestId}/package/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        /** Short-lived link to the granted package (registered as a download) */
        get: operations["downloadAccessPackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/access-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who accessed my declaration (register entries visible to the declarant) */
        get: operations["getMyAccessHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/certified-copies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My certified copies with download links */
        get: operations["listMyCertifiedCopies"];
        put?: never;
        /** Certified copy of one of my submitted versions */
        post: operations["requestCertifiedCopy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/access/requests/{requestId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant, partially grant or deny (final; Regulation 24 grounds required for partial and deny) */
        post: operations["decideAccessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lea/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The officer's requests */
        get: operations["listMyLeaRequests"];
        put?: never;
        /** Law-enforcement officer submits a written request (no Form K); allocates the LEA reference */
        post: operations["submitLeaRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lea/requests/{leaRequestId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaRequestId: components["parameters"]["LeaRequestId"];
            };
            cookie?: never;
        };
        /** One request (officer who filed it, or the Commission's access officer) */
        get: operations["getLeaRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lea/requests/{leaRequestId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaRequestId: components["parameters"]["LeaRequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Access officer records the provenance and reason check and resolves the officer */
        post: operations["verifyLeaRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lea/requests/{leaRequestId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaRequestId: components["parameters"]["LeaRequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant (package, declarant notified after) or deny with reasons */
        post: operations["decideLeaRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lea/requests/{leaRequestId}/package/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaRequestId: components["parameters"]["LeaRequestId"];
            };
            cookie?: never;
        };
        /** Short-lived link to the granted package (registered) */
        get: operations["downloadLeaPackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AccessRequestStatus: "submitted" | "pending-applicant-verification" | "officer-unresolved" | "awaiting-representations" | "under-decision" | "granted" | "partially-granted" | "denied" | "cannot-identify" | "withdrawn";
        /** @enum {string} */
        Outcome: "grant" | "partial-grant" | "deny";
        /**
         * @description Regulation 24
         * @enum {string}
         */
        Ground: "public-interest" | "prejudice-proceeding" | "frivolous-vexatious" | "not-objectives";
        /** @enum {string} */
        Section: "bio" | "income" | "assets" | "liabilities" | "other";
        Scope: {
            years: number[];
            includeSpouses: boolean;
            includeChildren: boolean;
            sections: components["schemas"]["Section"][];
            includeClarifications: boolean;
        };
        Decision: {
            outcome: components["schemas"]["Outcome"];
            grantedScope: components["schemas"]["Scope"] | null;
            grounds: components["schemas"]["Ground"][];
            reasons: string;
            decidedBy: {
                subject: string;
                name: string;
            };
            /** Format: date-time */
            decidedAt: string;
        };
        Package: {
            /** Format: uuid */
            documentId: string;
            verificationId: string;
            /** Format: date-time */
            issuedAt: string;
            /** Format: date-time */
            downloadExpiresAt: string;
            downloads: number;
        };
        /** @description A form-k.v1 document (packages/schemas/forms/form-k.v1.json) */
        FormK: {
            [key: string]: unknown;
        };
        AccessRequest: {
            /** Format: uuid */
            id: string;
            /** @description ARQ-<ISSUER>-<YEAR>-<seq>-<check> */
            reference: string;
            commission: {
                slug: string;
                name: string;
            };
            status: components["schemas"]["AccessRequestStatus"];
            /** @description The form-k.v1 document as submitted */
            formK: components["schemas"]["FormK"];
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            decisionDeadlineAt: string;
            decision: components["schemas"]["Decision"] | null;
            package: components["schemas"]["Package"] | null;
            timeline: components["schemas"]["RegisterEntry"][];
        };
        RegisterEntry: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "received" | "verified" | "notified" | "representations" | "decided" | "package-issued" | "downloaded" | "expired" | "withdrawn" | "cannot-identify" | "self-access";
            /** Format: date-time */
            at: string;
            actor: string | null;
            summary: string;
            reference: string;
        };
        Representations: {
            /** @enum {string} */
            stance: "object" | "consent" | "context";
            text: string;
            attachments: {
                /** Format: uuid */
                uploadId: string;
                fileName: string;
            }[];
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OfficerRequestView: {
            /** Format: uuid */
            id: string;
            /** @description ARQ-<ISSUER>-<YEAR>-<seq>-<check> */
            reference: string;
            commission: {
                slug: string;
                name: string;
            };
            status: components["schemas"]["AccessRequestStatus"];
            /** @description The form-k.v1 document as submitted */
            formK: components["schemas"]["FormK"];
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            decisionDeadlineAt: string;
            decision: components["schemas"]["Decision"] | null;
            package: components["schemas"]["Package"] | null;
            timeline: components["schemas"]["RegisterEntry"][];
            /** @enum {string} */
            applicantIdentityStatus: "verified" | "pending-verification";
            resolvedRosterRecordId: string | null;
            representations: components["schemas"]["Representations"] | null;
            windowEndsAt: string | null;
        };
        VerifyApplicantIdentity: {
            verified: boolean;
            note: string;
        };
        QueueItem: {
            /** @enum {string} */
            kind: "form-k" | "lea";
            /** Format: uuid */
            id: string;
            reference: string;
            applicantOrAgency: string;
            officerSought: string;
            resolvedName: string | null;
            status: components["schemas"]["AccessRequestStatus"];
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            deadlineAt: string;
            windowEndsAt: string | null;
            late: boolean;
        };
        QueuePage: {
            items: components["schemas"]["QueueItem"][];
            /** @description Pass as `cursor` for the next page; null on the last page */
            nextCursor: string | null;
        };
        ResolveOfficer: {
            /** @description The roster record of the Commission the officer named in Part II is (an onboarded one: the declarant is notified); null records that they cannot be identified, which closes the request */
            rosterRecordId: string | null;
        };
        RosterCandidate: {
            /** Format: uuid */
            id: string;
            personnelFileNumber: string;
            fullName: string;
            designation: string | null;
            /** @description Its name */
            reportingEntity: string | null;
            /** @description The roster record state: not_onboarded, onboarded, exited */
            state: string;
            onboarded: boolean;
        };
        RosterCandidates: {
            /** @description By full name, at most 20 */
            items: components["schemas"]["RosterCandidate"][];
        };
        RepresentationsInput: {
            /**
             * @description `object` to the disclosure, `consent` to it (the request goes under decision at once), or add `context`
             * @enum {string}
             */
            stance: "object" | "consent" | "context";
            /** @description The declarant's representations; may be empty only with `consent` */
            text: string;
            /** @description Clean uploads of purpose `access-representation` by the declarant */
            attachments: string[];
        };
        DeclarantNotice: {
            /** Format: uuid */
            requestId: string;
            reference: string;
            /** @enum {string} */
            kind: "form-k" | "lea";
            commission: {
                slug: string;
                name: string;
            };
            status: components["schemas"]["AccessRequestStatus"];
            applicantName: string;
            purposeInGeneralTerms: string;
            scope: components["schemas"]["Scope"];
            /** Format: date-time */
            notifiedAt: string;
            windowEndsAt: string | null;
            canRespond: boolean;
            representations: components["schemas"]["Representations"] | null;
            decision: components["schemas"]["Decision"] | null;
        };
        ProblemDetails: {
            type: string;
            title: string;
            status: number;
            /**
             * @description Machine-readable cause, from the platform registry; clients map it to copy and never show `title` or `detail`
             * @enum {string}
             */
            code?: "database-unavailable" | "rate-limit-exceeded" | "no-match" | "already-onboarded" | "no-roster" | "otp-invalid" | "otp-expired" | "resend-cooldown" | "otp-send-failed" | "wrong-step" | "session-expired" | "iprs-unavailable" | "identity-unavailable" | "email-in-use" | "identity-mismatch" | "step-up-required" | "incomplete" | "before-statement-date" | "amendment-window-closed" | "not-a-draft" | "not-submitted" | "obligation-cancelled" | "acknowledgement-issued" | "acknowledgement-in-progress" | "no-applicant-record" | "request-decided" | "request-closed" | "officer-resolved" | "not-under-decision" | "not-pending-verification" | "representations-closed" | "download-expired" | "scope-exceeds-request" | "grounds-required";
            detail?: string;
            instance?: string;
            /** @description Field-level errors; `path` is the dotted request field */
            errors?: {
                path: string;
                message: string;
            }[];
        };
        /** @enum {string} */
        LeaRequestStatus: "received" | "verified" | "granted" | "denied" | "withdrawn";
        DecisionInput: {
            outcome: components["schemas"]["Outcome"];
            /** @description Required for partial-grant; must be a subset of the requested scope */
            grantedScope?: components["schemas"]["Scope"] | null;
            /** @description Required for partial-grant and deny */
            grounds?: components["schemas"]["Ground"][];
            reasons: string;
        };
        CertifiedCopy: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            declarationId: string;
            version: number;
            /** @enum {string} */
            status: "pending" | "issued" | "failed";
            /** Format: uuid */
            documentId: string | null;
            verificationId: string | null;
            /** Format: uri */
            downloadUrl: string | null;
            /** Format: date-time */
            requestedAt: string;
        };
        LeaRequestInput: {
            commission: string;
            officerSought: {
                name: string;
                entity?: string;
                workStation?: string;
                personnelFileNumber?: string;
            };
            reason: string;
            caseReference: string;
            scope: components["schemas"]["Scope"];
        };
        LeaRequest: {
            /** Format: uuid */
            id: string;
            /** @description LEA-<ISSUER>-<YEAR>-<seq>-<check> */
            reference: string;
            commission: {
                slug: string;
                name: string;
            };
            agency: {
                code: string;
                name: string;
            };
            officer: {
                subject: string;
                name: string;
            };
            officerSought: {
                [key: string]: unknown;
            };
            reason: string;
            caseReference: string;
            scope: components["schemas"]["Scope"];
            status: components["schemas"]["LeaRequestStatus"];
            /** Format: date-time */
            receivedAt: string;
            /** Format: date-time */
            deadlineAt: string;
            verification: {
                by: string;
                /** Format: date-time */
                at: string;
                note: string;
            } | null;
            decision: components["schemas"]["Decision"] | null;
            package: components["schemas"]["Package"] | null;
            timeline: components["schemas"]["RegisterEntry"][];
        };
        DownloadLink: {
            /** Format: uri */
            downloadUrl: string;
            /** Format: date-time */
            expiresAt: string;
            sha256: string;
        };
    };
    responses: {
        /** @description Not found, or not visible to the caller */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Caller lacks the required role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request failed validation */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        RequestId: string;
        LeaRequestId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMyAccessRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequest"][];
                };
            };
            /**
             * @description Not an applicant, or problem code `no-applicant-record`
             *
             *     Requires one of the roles: applicant
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The key service cannot be reached */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    submitAccessRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUID, unique per logical request; reuse on retry */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormK"];
            };
        };
        responses: {
            /** @description Received */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequest"];
                };
            };
            /** @description Not a valid form-k.v1 document (`errors` name the paths), or no such Responsible Commission */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /**
             * @description Problem code `no-applicant-record`: the account has no applicant person record
             *
             *     Requires one of the roles: applicant
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Idempotency-Key reused with a different request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The directory or the key service cannot be reached; nothing was stored */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getMyAccessRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequest"];
                };
            };
            /** @description requestId is not a UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /**
             * @description Not an applicant, or problem code `no-applicant-record`
             *
             *     Requires one of the roles: applicant
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such request of the applicant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The key service cannot be reached */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    withdrawAccessRequest: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. Client-generated UUID, unique per logical request; reuse on retry and the stored answer is replayed instead of acting twice */
                "Idempotency-Key"?: string;
            };
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequest"];
                };
            };
            /** @description requestId is not a UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /**
             * @description Not an applicant, or problem code `no-applicant-record`
             *
             *     Requires one of the roles: applicant
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such request of the applicant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem code `request-decided` (a decision is final) or `request-closed` (withdrawn already, or the officer could not be identified) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Idempotency-Key reused with a different request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listCommissionAccessRequests: {
        parameters: {
            query?: {
                /** @description Only requests in these statuses, comma-separated (e.g. the open ones: `submitted,pending-applicant-verification,officer-unresolved,awaiting-representations,under-decision`) */
                status?: string;
                /** @description Only Form K or only LEA requests */
                kind?: "form-k" | "lea";
                /** @description `nextCursor` of the previous page; omit for the first page */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuePage"];
                };
            };
            /** @description Query failed validation, or an unknown cursor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Requires one of the roles: access-officer, supervisor, eacc-analyst, eacc-supervisor */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not the caller's Commission */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getAccessRequestForOfficer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficerRequestView"];
                };
            };
            /** @description requestId is not a UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Requires one of the roles: access-officer, supervisor, eacc-analyst, eacc-supervisor */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such request at the caller's Commission (another Commission's, EACC's or anyone else's view) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The key service cannot be reached */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listRosterCandidates: {
        parameters: {
            query: {
                /** @description A personnel file number or its beginning, or part of a name (both case-insensitive) */
                q: string;
            };
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterCandidates"];
                };
            };
            /** @description requestId is not a UUID, or no search of at least 2 characters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /**
             * @description The Commission supervisor reads requests; only its access officer acts
             *
             *     Requires one of the roles: access-officer, supervisor, eacc-analyst, eacc-supervisor
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such request at the caller's Commission (another Commission's, EACC's or anyone else's view) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The directory cannot be reached */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    resolveRequestedOfficer: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. Client-generated UUID, unique per logical request; reuse on retry and the stored answer is replayed instead of acting twice */
                "Idempotency-Key"?: string;
            };
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveOfficer"];
            };
        };
        responses: {
            /** @description Resolved; the declarant notification follows, or the request is closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficerRequestView"];
                };
            };
            /** @description requestId is not a UUID, the body failed validation, or `rosterRecordId` is not an onboarded roster record of the Commission */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /**
             * @description The Commission supervisor reads requests; only its access officer acts
             *
             *     Requires one of the roles: access-officer, supervisor, eacc-analyst, eacc-supervisor
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such request at the caller's Commission (another Commission's, EACC's or anyone else's view) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem code `officer-resolved` (once only), `request-closed` or `request-decided`; or the applicant's identity is still to be verified */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Idempotency-Key reused with a different request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The directory cannot be reached; nothing was recorded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    verifyApplicantIdentity: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. Client-generated UUID, unique per logical request; reuse on retry and the stored answer is replayed instead of acting twice */
                "Idempotency-Key"?: string;
            };
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyApplicantIdentity"];
            };
        };
        responses: {
            /** @description Recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficerRequestView"];
                };
            };
            /** @description requestId is not a UUID, or the body failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /**
             * @description The Commission supervisor reads requests; only its access officer acts
             *
             *     Requires one of the roles: access-officer, supervisor
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such request at the Commission */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem code `not-pending-verification`: the request is not waiting for the applicant's identity */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Idempotency-Key reused with a different request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The directory cannot be reached; nothing was recorded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listMyAccessNotices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeclarantNotice"][];
                };
            };
            /** @description Requires one of the roles: declarant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not a declarant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The key service cannot be reached */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    submitRepresentations: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. Client-generated UUID, unique per logical request; reuse on retry and the stored answer is replayed instead of acting twice */
                "Idempotency-Key"?: string;
            };
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepresentationsInput"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeclarantNotice"];
                };
            };
            /** @description requestId is not a UUID, the body failed validation, or an attachment is not a clean `access-representation` upload of the declarant */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Requires one of the roles: declarant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such request about the declarant that they were notified of */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem code `representations-closed`: the window has closed (or the declarant consented, or the request closed) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Idempotency-Key reused with a different request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Documents or the key service cannot be reached; nothing was saved */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listAccessCommissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        slug: string;
                        name: string;
                        years: number[];
                    }[];
                };
            };
        };
    };
    downloadAccessPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadLink"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Download window expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getMyAccessHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterEntry"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listMyCertifiedCopies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Copies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertifiedCopy"][];
                };
            };
        };
    };
    requestCertifiedCopy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    declarationId: string;
                    version: number;
                };
            };
        };
        responses: {
            /** @description Issuance requested; poll the copy */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertifiedCopy"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    decideAccessRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            /** @description Decided; notifications and package follow */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficerRequestView"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Already decided or not yet under decision */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listMyLeaRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaRequest"][];
                };
            };
        };
    };
    submitLeaRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaRequestInput"];
            };
        };
        responses: {
            /** @description Received */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaRequest"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["Forbidden"];
        };
    };
    getLeaRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaRequestId: components["parameters"]["LeaRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaRequest"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    verifyLeaRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaRequestId: components["parameters"]["LeaRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    rosterRecordId: string | null;
                    note: string;
                };
            };
        };
        responses: {
            /** @description Verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaRequest"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    decideLeaRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                leaRequestId: components["parameters"]["LeaRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            /** @description Decided */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaRequest"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Already decided */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    downloadLeaPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leaRequestId: components["parameters"]["LeaRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadLink"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Download window expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
