# Generated by Django 6.1.1 on 2026-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(db_index=True, max_length=10)),
                ('personal_number', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('employer_code', models.CharField(max_length=20)),
                ('employer_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=100)),
                ('job_group', models.CharField(max_length=5)),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited')], max_length=10)),
                ('exit_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id_number', '-appointment_date'],
                'constraints': [models.UniqueConstraint(fields=('employer_code', 'personal_number'), name='hr_unique_personal_number')],
            },
        ),
    ]
