# Generated by Django 6.1.1 on 2026-09-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_code', models.CharField(db_index=True, max_length=20)),
                ('registration_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['employer_code', 'registration_number'],
                'constraints': [models.UniqueConstraint(fields=('employer_code', 'registration_number'), name='hr_unique_employer_supplier')],
            },
        ),
    ]
