/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/v1/iprs/person-lookups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Person as held by IPRS, cached for 24 hours (hits and misses)
         * @description A read, posted so the national ID travels in the body rather than the URL (URLs end up in access logs, traces and problem details). Safe to repeat. Requires a service token with scope `iprs`.
         */
        post: operations["lookupIprsPerson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/kra/taxpayers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KRA PIN(s), taxpayer and compliance for a national ID */
        get: operations["lookupKraTaxpayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/ntsa/owners/{nationalId}/vehicles": {
        parameters: {
            query?: never;
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path: {
                nationalId: components["parameters"]["NationalIdPath"];
            };
            cookie?: never;
        };
        /** Vehicles registered to a national ID */
        get: operations["lookupNtsaVehicles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/brs/persons/{nationalId}/directorships": {
        parameters: {
            query?: never;
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path: {
                nationalId: components["parameters"]["NationalIdPath"];
            };
            cookie?: never;
        };
        /** Directorships and shareholdings of a national ID */
        get: operations["lookupBrsDirectorships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/brs/companies/{registrationNumber}/supplies": {
        parameters: {
            query: {
                employerCode: string;
            };
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path: {
                registrationNumber: string;
            };
            cookie?: never;
        };
        /** Whether a company appears in an employer's supplier list (HR mock) */
        get: operations["checkCompanySuppliesEmployer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/ardhisasa/owners/{nationalId}/parcels": {
        parameters: {
            query?: never;
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path: {
                nationalId: components["parameters"]["NationalIdPath"];
            };
            cookie?: never;
        };
        /** Land parcels registered to a national ID */
        get: operations["lookupArdhisasaParcels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/verification-results/{resultId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resultId: string;
            };
            cookie?: never;
        };
        /** A stored lookup result, decrypted for the requesting tenant's services (audited) */
        get: operations["getVerificationResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-system call volume, cache hit rate, breaker state, last success (platform-admin) */
        get: operations["getIntegrationsCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/{system}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: components["parameters"]["System"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force lookups to unavailable during a known outage (platform-admin) */
        post: operations["pauseIntegration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/{system}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: components["parameters"]["System"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume lookups (platform-admin) */
        post: operations["resumeIntegration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/payroll/instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a stop or resume salary instruction to payroll (idempotent by instruction reference) */
        post: operations["submitPayrollInstruction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/payroll/instructions/{instructionReference}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instructionReference: string;
            };
            cookie?: never;
        };
        /** Stored instruction and acknowledgement */
        get: operations["getPayrollInstruction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/icms/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a referral with ICMS and return the case number (idempotent by referral reference) */
        post: operations["submitIcmsReferral"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/icms/referrals/{referralReference}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                referralReference: string;
            };
            cookie?: never;
        };
        /** Stored ICMS registration for a referral reference */
        get: operations["getIcmsReferral"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LookupIprsPerson: {
            nationalId: string;
        };
        /** @description A person as IPRS holds them */
        IprsPerson: {
            nationalId: string;
            firstName: string;
            middleName: string | null;
            lastName: string;
            /** Format: date */
            dateOfBirth: string;
            /** @enum {string} */
            sex: "F" | "M";
        };
        ProblemDetails: {
            type: string;
            title: string;
            status: number;
            /**
             * @description Machine-readable cause, from the platform registry; clients map it to copy and never show `title` or `detail`
             * @enum {string}
             */
            code?: "database-unavailable" | "rate-limit-exceeded" | "no-match" | "already-onboarded" | "no-roster" | "otp-invalid" | "otp-expired" | "resend-cooldown" | "otp-send-failed" | "wrong-step" | "session-expired" | "iprs-unavailable" | "identity-unavailable" | "email-in-use" | "step-up-required" | "incomplete" | "before-statement-date" | "amendment-window-closed" | "not-a-draft" | "not-submitted" | "obligation-cancelled" | "acknowledgement-issued" | "acknowledgement-in-progress" | "no-applicant-record" | "request-decided" | "request-closed" | "officer-resolved" | "not-under-decision" | "not-pending-verification" | "representations-closed" | "download-expired" | "scope-exceeds-request" | "grounds-required";
            detail?: string;
            instance?: string;
            /** @description Field-level errors; `path` is the dotted request field */
            errors?: {
                path: string;
                message: string;
            }[];
        };
        /** @enum {string} */
        System: "iprs" | "kra" | "ntsa" | "brs" | "ardhisasa" | "payroll" | "icms";
        /** @enum {string} */
        LookupOutcome: "found" | "not-found" | "unavailable";
        /** @enum {string} */
        UnavailableReason: "timeout" | "breaker-open" | "paused" | "upstream-error";
        ResultEnvelope: {
            /** Format: uuid */
            resultId: string;
            system: components["schemas"]["System"];
            outcome: components["schemas"]["LookupOutcome"];
            reason: components["schemas"]["UnavailableReason"] | null;
            cached: boolean;
            /** Format: date-time */
            checkedAt: string;
        };
        KraResult: components["schemas"]["ResultEnvelope"] & {
            taxpayers: {
                pin: string;
                /** Format: date */
                registeredOn: string;
                compliance: {
                    /** @enum {string} */
                    status: "compliant" | "non-compliant" | "unknown";
                    certificateNumber: string | null;
                    /** Format: date */
                    validUntil: string | null;
                    annualIncomeDeclaredCents: number | null;
                };
            }[];
        };
        NtsaResult: components["schemas"]["ResultEnvelope"] & {
            vehicles: {
                registrationNumber: string;
                make: string;
                model: string;
                yearOfManufacture: number;
                /** Format: date */
                registeredOn: string;
            }[];
        };
        BrsResult: components["schemas"]["ResultEnvelope"] & {
            directorships: {
                companyRegistrationNumber: string;
                companyName: string;
                companyStatus: string;
                role: string;
                shares: number | null;
                /** Format: date */
                appointedOn: string;
            }[];
        };
        SupplierCheckResult: components["schemas"]["ResultEnvelope"] & {
            /** @description null when unavailable */
            supplies: boolean | null;
        };
        ArdhisasaResult: components["schemas"]["ResultEnvelope"] & {
            parcels: {
                parcelNumber: string;
                county: string;
                areaHectares: number;
                tenure: string;
                /** Format: date */
                registeredOn: string;
            }[];
        };
        StoredResult: {
            /** Format: uuid */
            resultId: string;
            system: components["schemas"]["System"];
            outcome: components["schemas"]["LookupOutcome"];
            /** Format: date-time */
            checkedAt: string;
            legalBasis: string;
            /** @description The normalised records as returned by the lookup */
            payload: {
                [key: string]: unknown;
            };
        };
        SystemCoverage: {
            system: components["schemas"]["System"];
            calls24h: number;
            cacheHitRate: number;
            /** @enum {string} */
            breaker: "closed" | "open" | "half-open";
            /** Format: date-time */
            lastSuccessAt: string | null;
            paused: boolean;
            rateLimitPerMinute: number;
            cacheTtlSeconds: number;
        };
        /** @enum {string} */
        PayrollAction: "stop_salary" | "resume_salary";
        PayrollInstructionRequest: {
            /** @description The ADM reference (stop) or ADM reference with -R suffix (resume) */
            instructionReference: string;
            employerCode: string;
            personalNumber: string;
            nationalId: string;
            action: components["schemas"]["PayrollAction"];
            reason: string;
            /** Format: date */
            effectiveDate: string;
        };
        PayrollInstruction: {
            instructionReference: string;
            action: components["schemas"]["PayrollAction"];
            /** @enum {string} */
            status: "accepted" | "pending" | "failed";
            payrollReference: string | null;
            /** Format: date-time */
            receivedAt: string | null;
            /** Format: date-time */
            sentAt: string;
        };
        IcmsReferralRequest: {
            /** @description The RFL reference */
            referralReference: string;
            nationalId: string;
            fullName: string;
            /** @description Issuer code */
            referringCommission: string;
            grounds: string;
            details: string;
        };
        IcmsReferral: {
            referralReference: string;
            caseNumber: string | null;
            /** @enum {string} */
            status: "registered" | "pending" | "failed";
            /** Format: date-time */
            registeredAt: string | null;
            /** Format: date-time */
            sentAt: string;
        };
    };
    responses: {
        /** @description X-Legal-Basis header missing or unknown */
        MissingLegalBasis: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        NationalIdPath: string;
        NationalIdQuery: string;
        /** @description Review case the lookup is for; recorded on the result and the audit event */
        CaseRef: string;
        /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
        LegalBasis: string;
        System: components["schemas"]["System"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    lookupIprsPerson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LookupIprsPerson"];
            };
        };
        responses: {
            /** @description Person found */
            200: {
                headers: {
                    /** @description `hit` when the answer came from the cache, `miss` when IPRS was asked */
                    "X-Cache"?: "hit" | "miss";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IprsPerson"];
                };
            };
            /** @description National ID missing or malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Requires one of the scopes: iprs */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem type `not-found`: IPRS has no person with this national ID */
            404: {
                headers: {
                    /** @description `hit` when the answer came from the cache, `miss` when IPRS was asked */
                    "X-Cache"?: "hit" | "miss";
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem type `upstream-unavailable`: circuit open or timeout */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    lookupKraTaxpayer: {
        parameters: {
            query: {
                nationalId: components["parameters"]["NationalIdQuery"];
            };
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result (found, not-found or unavailable) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KraResult"];
                };
            };
            400: components["responses"]["MissingLegalBasis"];
        };
    };
    lookupNtsaVehicles: {
        parameters: {
            query?: never;
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path: {
                nationalId: components["parameters"]["NationalIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NtsaResult"];
                };
            };
            400: components["responses"]["MissingLegalBasis"];
        };
    };
    lookupBrsDirectorships: {
        parameters: {
            query?: never;
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path: {
                nationalId: components["parameters"]["NationalIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrsResult"];
                };
            };
            400: components["responses"]["MissingLegalBasis"];
        };
    };
    checkCompanySuppliesEmployer: {
        parameters: {
            query: {
                employerCode: string;
            };
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path: {
                registrationNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierCheckResult"];
                };
            };
            400: components["responses"]["MissingLegalBasis"];
        };
    };
    lookupArdhisasaParcels: {
        parameters: {
            query?: never;
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path: {
                nationalId: components["parameters"]["NationalIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArdhisasaResult"];
                };
            };
            400: components["responses"]["MissingLegalBasis"];
        };
    };
    getVerificationResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resultId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredResult"];
                };
            };
            /** @description Not found or other tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getIntegrationsCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coverage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemCoverage"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    pauseIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: components["parameters"]["System"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemCoverage"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    resumeIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system: components["parameters"]["System"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemCoverage"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    submitPayrollInstruction: {
        parameters: {
            query?: never;
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayrollInstructionRequest"];
            };
        };
        responses: {
            /** @description Already submitted (replay) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayrollInstruction"];
                };
            };
            /** @description Acknowledged by payroll */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayrollInstruction"];
                };
            };
            400: components["responses"]["MissingLegalBasis"];
            /** @description Payroll unavailable; nothing recorded as sent */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getPayrollInstruction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instructionReference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instruction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayrollInstruction"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    submitIcmsReferral: {
        parameters: {
            query?: never;
            header: {
                /** @description Review case the lookup is for; recorded on the result and the audit event */
                "X-Case-Ref"?: components["parameters"]["CaseRef"];
                /** @description e.g. regs-r20-1-b, act-s35-5, adr-014-onboarding, declarant-request (lookups the declarant asked for while filing; DPA s.30(1)(a)) */
                "X-Legal-Basis": components["parameters"]["LegalBasis"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IcmsReferralRequest"];
            };
        };
        responses: {
            /** @description Already registered (replay) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IcmsReferral"];
                };
            };
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IcmsReferral"];
                };
            };
            400: components["responses"]["MissingLegalBasis"];
            /** @description ICMS unavailable; nothing registered */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getIcmsReferral: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                referralReference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IcmsReferral"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
