import { Logger } from '@nestjs/common';
import { ProblemException } from '@adili/api-kit';
import { sql } from 'drizzle-orm';
import { drizzle, type NodePgDatabase } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import pg from 'pg';

export type Database<TSchema extends Record<string, unknown> = Record<string, never>> =
  NodePgDatabase<TSchema> & { $client: pg.Pool };

export interface DatabaseOptions<TSchema extends Record<string, unknown>> {
  url: string;
  schema: TSchema;
  /** Shown in `pg_stat_activity`. */
  applicationName: string;
  maxConnections?: number;
  /** How long to wait for a new connection before failing as unavailable. */
  connectTimeoutMillis?: number;
}

/**
 * Covers a new Postgres session (a backend fork and SCRAM exchange) on a loaded host, which takes
 * seconds, plus the event-loop lag of a busy process, whose timers can fire before the socket that
 * already answered is read. A refused or reset connection fails at once regardless; this bounds only
 * a database that accepts and never answers.
 */
const DEFAULT_CONNECT_TIMEOUT_MILLIS = 10_000;

export function createDatabase<TSchema extends Record<string, unknown>>(
  options: DatabaseOptions<TSchema>,
): Database<TSchema> {
  const pool = new UnavailableAwarePool({
    connectionString: options.url,
    application_name: options.applicationName,
    max: options.maxConnections ?? 10,
    // Keep one connection open through quiet spells, so the next request does not pay for a
    // new Postgres session (a backend fork and SCRAM exchange, seconds on a starved host).
    min: 1,
    // Bounded, so requests fail as unavailable instead of queueing behind a black-holed database.
    connectionTimeoutMillis: options.connectTimeoutMillis ?? DEFAULT_CONNECT_TIMEOUT_MILLIS,
  });
  // An idle connection the server drops (restart, failover, admin terminate) is emitted here;
  // unhandled, it would crash the process. The pool has already discarded the client.
  pool.on('error', (error) => {
    logger.warn({ err: error }, 'Idle database connection lost; the pool will open a new one');
  });
  // A checked-out connection (a transaction's) has no pool listener: the pool removes its idle
  // listener on checkout. Dropped then, its 'error' would be unhandled and end the process
  // (#636). Its query fails on its own; on release the pool discards the broken client.
  pool.on('acquire', (client) => client.on('error', onCheckedOutError));
  pool.on('release', (_error, client) => client.removeListener('error', onCheckedOutError));
  return drizzle({ client: pool, schema: options.schema, casing: 'snake_case' });
}

const logger = new Logger('Database');

function onCheckedOutError(error: Error): void {
  logger.warn({ err: error }, 'Database connection lost while in use; its work fails');
}

/**
 * The database could not be reached: no connection within the timeout, refused, or the server
 * turned the session away. Rendered as 503 so callers treat it as transient, not as a defect.
 */
export class DatabaseUnavailableError extends ProblemException {
  constructor(cause: unknown) {
    const { problem, extensions } = ProblemException.fromCode('database-unavailable');
    super(problem, extensions);
    this.cause = cause;
  }
}

type ConnectCallback = (
  error: Error | undefined,
  client: pg.PoolClient | undefined,
  release: (release?: unknown) => void,
) => void;

/** A pool whose connect failures are `DatabaseUnavailableError`s, for queries and transactions. */
class UnavailableAwarePool extends pg.Pool {
  override connect(): Promise<pg.PoolClient>;
  override connect(callback: ConnectCallback): void;
  override connect(callback?: ConnectCallback): Promise<pg.PoolClient> | void {
    if (!callback) {
      return super.connect().catch((error: unknown) => {
        throw new DatabaseUnavailableError(error);
      });
    }
    // pg-pool's own `query` connects through this callback form.
    super.connect((error, client, release) => {
      callback(error ? new DatabaseUnavailableError(error) : undefined, client, release);
    });
  }
}

/** Applies pending SQL migrations generated by drizzle-kit. */
export async function runMigrations(url: string, migrationsFolder: string): Promise<void> {
  const pool = new pg.Pool({ connectionString: url, max: 1 });
  try {
    await migrate(drizzle({ client: pool }), { migrationsFolder });
  } finally {
    await pool.end();
  }
}

export interface TenantContext {
  tenant: string;
  subject: string;
}

export interface PersonContext {
  /** The declarant's person, from the token's `person_id` claim (`Principal.personId`). */
  personId: string;
  subject: string;
}

type Transaction<TSchema extends Record<string, unknown>> = Parameters<
  Parameters<Database<TSchema>['transaction']>[0]
>[0];

/**
 * Runs `work` in a transaction scoped to one tenant. Row-level security policies read
 * `app.tenant` and `app.subject`; `set_config(..., true)` resets them when the transaction ends,
 * so pooled connections never leak context (ADR-006).
 */
export async function withTenant<TSchema extends Record<string, unknown>, TResult>(
  db: Database<TSchema>,
  context: TenantContext,
  work: (tx: Transaction<TSchema>) => Promise<TResult>,
): Promise<TResult> {
  return db.transaction(async (tx) => {
    await switchTenant(tx, context);
    return work(tx);
  });
}

/**
 * Runs `work` in a transaction scoped to one person, for a declarant's own data across
 * Commissions (ADR-018). Person policies read `app.person` (and `app.subject`), reset when the transaction
 * ends as with `withTenant`; `app.tenant` stays unset, so tenant policies admit nothing.
 *
 * A reset setting reads back as `''`, not null, on a connection that has had it: policies compare
 * with `nullif(current_setting('app.person', true), '')::uuid` so they neither fail nor match then.
 */
export async function withPerson<TSchema extends Record<string, unknown>, TResult>(
  db: Database<TSchema>,
  context: PersonContext,
  work: (tx: Transaction<TSchema>) => Promise<TResult>,
): Promise<TResult> {
  return db.transaction(async (tx) => {
    await tx.execute(
      sql`select set_config('app.person', ${context.personId}, true), set_config('app.subject', ${context.subject}, true)`,
    );
    return work(tx);
  });
}

/**
 * Re-scopes a `withTenant` transaction to another tenant for the rest of it (ADR-006), e.g. a
 * public route that finds a row in the platform context and then works on it as its tenant.
 * Rows read before stay readable in memory; later statements see only the new tenant's rows.
 * Like `withTenant`, the setting ends with the transaction.
 */
export async function switchTenant<TSchema extends Record<string, unknown>>(
  tx: Transaction<TSchema>,
  context: TenantContext,
): Promise<void> {
  await tx.execute(
    sql`select set_config('app.tenant', ${context.tenant}, true), set_config('app.subject', ${context.subject}, true)`,
  );
}
