import { sql } from 'drizzle-orm';
import { drizzle, type NodePgDatabase } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import pg from 'pg';

export type Database<TSchema extends Record<string, unknown> = Record<string, never>> =
  NodePgDatabase<TSchema> & { $client: pg.Pool };

export interface DatabaseOptions<TSchema extends Record<string, unknown>> {
  url: string;
  schema: TSchema;
  /** Shown in `pg_stat_activity`. */
  applicationName: string;
  maxConnections?: number;
}

export function createDatabase<TSchema extends Record<string, unknown>>(
  options: DatabaseOptions<TSchema>,
): Database<TSchema> {
  const pool = new pg.Pool({
    connectionString: options.url,
    application_name: options.applicationName,
    max: options.maxConnections ?? 10,
    // Fail fast instead of queueing requests behind a dead database.
    connectionTimeoutMillis: 2_000,
  });
  return drizzle({ client: pool, schema: options.schema, casing: 'snake_case' });
}

/** Applies pending SQL migrations generated by drizzle-kit. */
export async function runMigrations(url: string, migrationsFolder: string): Promise<void> {
  const pool = new pg.Pool({ connectionString: url, max: 1 });
  try {
    await migrate(drizzle({ client: pool }), { migrationsFolder });
  } finally {
    await pool.end();
  }
}

export interface TenantContext {
  tenant: string;
  subject: string;
}

export interface PersonContext {
  /** The declarant's person, from the token's `person_id` claim (`Principal.personId`). */
  personId: string;
  subject: string;
}

type Transaction<TSchema extends Record<string, unknown>> = Parameters<
  Parameters<Database<TSchema>['transaction']>[0]
>[0];

/**
 * Runs `work` in a transaction scoped to one tenant. Row-level security policies read
 * `app.tenant` and `app.subject`; `set_config(..., true)` resets them when the transaction ends,
 * so pooled connections never leak context (ADR-006).
 */
export async function withTenant<TSchema extends Record<string, unknown>, TResult>(
  db: Database<TSchema>,
  context: TenantContext,
  work: (tx: Transaction<TSchema>) => Promise<TResult>,
): Promise<TResult> {
  return db.transaction(async (tx) => {
    await tx.execute(
      sql`select set_config('app.tenant', ${context.tenant}, true), set_config('app.subject', ${context.subject}, true)`,
    );
    return work(tx);
  });
}

/**
 * Runs `work` in a transaction scoped to one person, for a declarant's own data across
 * Commissions. Person policies read `app.person` (and `app.subject`), reset when the transaction
 * ends as with `withTenant`; `app.tenant` stays unset, so tenant policies admit nothing.
 *
 * A reset setting reads back as `''`, not null, on a connection that has had it: policies compare
 * with `nullif(current_setting('app.person', true), '')::uuid` so they neither fail nor match then.
 */
export async function withPerson<TSchema extends Record<string, unknown>, TResult>(
  db: Database<TSchema>,
  context: PersonContext,
  work: (tx: Transaction<TSchema>) => Promise<TResult>,
): Promise<TResult> {
  return db.transaction(async (tx) => {
    await tx.execute(
      sql`select set_config('app.person', ${context.personId}, true), set_config('app.subject', ${context.subject}, true)`,
    );
    return work(tx);
  });
}
