# Generated by Django 6.1.1 on 2026-09-25 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('instruction_reference', models.CharField(max_length=40, unique=True)),
                ('employer_code', models.CharField(max_length=20)),
                ('personal_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('stop_salary', 'Stop salary pending compliance'), ('resume_salary', 'Resume salary')], max_length=20)),
                ('reason', models.TextField()),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted')], default='accepted', max_length=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
