# Generated by Django 6.1.1 on 2026-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('referral_reference', models.CharField(max_length=40, unique=True)),
                ('id_number', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('referring_commission', models.CharField(max_length=20)),
                ('grounds', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('registered', 'Registered')], default='registered', max_length=12)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
