# Generated by Django 6.1.1 on 2026-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxpayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=11, unique=True)),
                ('id_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('registered_on', models.DateField()),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-compliant')], max_length=20)),
                ('compliance_certificate_number', models.CharField(blank=True, max_length=30)),
                ('compliance_valid_until', models.DateField(blank=True, null=True)),
                ('annual_income_declared', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'ordering': ['pin'],
            },
        ),
    ]
