/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/uploads': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reserve an upload and get a presigned PUT to quarantine
     * @description The purpose's roles only (roster-import: reporting-officer; declaration-attachment, clarification-attachment and action-response: declarant). The PUT URL is valid for 15 minutes and accepts exactly the declared Content-Type and size.
     */
    post: operations['createUpload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/uploads/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Upload state and metadata
     * @description Uploads of the caller's tenant whose purpose the caller's roles cover, and declaration attachments only to the declarant who uploaded them; any other is 404.
     */
    get: operations['getUpload'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/uploads/{id}/complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify, scan and move the uploaded object to the clean bucket
     * @description Synchronous, bounded by a 60-second budget. Returns the final state: clean, infected or rejected (type, size, missing, timeout). The quarantine object is deleted in every case.
     */
    post: operations['completeUpload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/v1/uploads/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Upload state and metadata, for services
     * @description Service tokens with scope documents:internal, acting for the tenant in X-Acting-Tenant. Any state; with who uploaded it and whether it is linked. Hands out no bytes, so unlike the download it is no audited read.
     */
    get: operations['getInternalUpload'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/v1/uploads/{id}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Short-lived presigned GET on a clean object, for services
     * @description Service tokens with scope documents:internal, acting for the tenant in X-Acting-Tenant. The URL is valid for 5 minutes. Audited under the tenant, naming whom the service reads for (X-Acting-Subject).
     */
    get: operations['getUploadDownload'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/v1/uploads/{id}/linked': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record that the owning service linked a clean upload
     * @description Service tokens with scope documents:internal, acting for the tenant in X-Acting-Tenant. The owning service calls it when it links a clean upload to its record (declarations: an attachment on an item), so the upload is not an orphan: a declaration attachment left unlinked for 30 days is deleted. Idempotent: the first link time is kept.
     */
    post: operations['markUploadLinked'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/v1/uploads/{id}/unlinked': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record that the owning service took its link to an upload back
     * @description Service tokens with scope documents:internal, acting for the tenant in X-Acting-Tenant. The owning service calls it when it removes the record an upload was linked to (declarations: an attachment unlinked, or a draft discarded); a declaration attachment left unlinked for 30 days is deleted. Idempotent: an upload that is not linked is left as it is.
     */
    post: operations['markUploadUnlinked'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/documents/{documentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Metadata of an issued document (owner)
     * @description The person the document is about; staff of the issuing Commission named among the document's additional downloaders; for a Commission's submitted Form M and its receipt, the Commission's supervisor, commission-admin, reporting officer or its federated system (a token of its tenant with scope reports:submit); for any Commission's Form M, its receipt or a referral package it sent EACC, an EACC analyst or supervisor (a token of the EACC tenant), refused the package that refers them when their token names them (`person_id`; staff tokens do not yet, #486); for EACC's national consolidated report (ncr), an EACC analyst or supervisor. Anyone else gets 404.
     */
    get: operations['getDocument'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/documents/{documentId}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Short-lived presigned download of an issued PDF (owner)
     * @description The document's subject person (the `person_id` of their token); an access officer of the issuing Commission named among the document's additional downloaders (their token's `sub`, tenant and role); for a Commission's submitted Form M and its receipt, the Commission's supervisor, commission-admin, reporting officer or its federated system (a token of its tenant with scope reports:submit); for any Commission's Form M, its receipt or a referral package it sent EACC, an EACC analyst or supervisor (a token of the EACC tenant), refused the package that refers them when their token names them (`person_id`; staff tokens do not yet, #486); for EACC's national consolidated report (ncr), an EACC analyst or supervisor (spec 09 authorisation; no other document is theirs to download). Anyone else gets 404. A document with a download window (an access package) is refused with 410 once it ends. Every download link handed out is audited under the issuing tenant (the Commission, or EACC for its NCR) and recorded as `document.downloaded.v1`, which the access register reads.
     */
    get: operations['getDocumentDownload'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/v1/documents/issue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Render, sign and register a document (services)
     * @description Service tokens with scope documents:internal, issuing for the tenant in X-Acting-Tenant. Renders the type's versioned template to PDF through Gotenberg with the verification code and QR in the footer of every page and the watermark, when given, across every page, PAdES-signs it with the documents signing certificate, stores its SHA-256 in an Ed25519-signed verification record, stores the PDF and emits `document.issued.v1`. The disclosure level and public payload are the template's. `downloadWindowDays` limits the subject person's downloads to that many days from issue. An access-package and an access-nil-letter require a watermark, a download window and a subject person; a certified-copy a subject person. A letter of the review service names its record, and its fields are pulled from the review service for the same tenant: a clarification-letter its clarification (internalGetClarificationLetterPayload), a decision-letter its determination (internalGetDeterminationLetterPayload), a notice-to-comply, warning, salary-stoppage or disciplinary-referral its administrative action (internalGetActionLetterPayload); the subject person must be the one the pulled payload names. A referral-package names its referral (internalGetReferralPackagePayload) and has no subject person; the declarant the pulled package names is never its subject person, and an EACC analyst or supervisor it refers is refused it when their token names them (staff tokens do not yet, #486). The reporting service's documents carry their payload and have no subject person: a form-m the submitted form-m.v1 document with its RPT reference, a compliance-report-receipt the report's reference, SHA-256 and time of receipt, an ncr (issued for the EACC tenant) the approved national consolidated report's aggregates and narrative. A portal link a letter prints (`portalUrl`, `respondUrl`) must be https in production. One document per type and subject: issuing again returns it with 200.
     */
    post: operations['issueDocument'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/v1/documents/{documentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Metadata of an issued document of the acting tenant (services)
     * @description Service tokens with scope documents:internal, acting in X-Acting-Tenant for the issuing tenant; a document another tenant issued is 404. The review service reads the SHA-256 of the letters it lists in a referral package's manifest (spec 08). Metadata only, no content or download link, so no audited read.
     */
    get: operations['internalGetDocument'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/v1/documents/{documentId}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Short-lived presigned download of an issued PDF (services)
     * @description Service tokens with scope documents:internal, acting for the tenant in X-Acting-Tenant: the issuing tenant's documents only. The service owning the record a document is about asks it for its staff (the review service for a reviewer opening a clarification letter), after checking the staff member may see that record; it audits that read with the staff member and the person. This read is audited too, under the issuing tenant, naming the person the document is about and the staff member the service reads for (X-Acting-Subject).
     */
    get: operations['internalGetDocumentDownload'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/v1/documents/{documentId}/supersede': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark a document superseded by a newer one (services)
     * @description Service tokens with scope documents:internal, acting for the tenant in X-Acting-Tenant. Sets the status to superseded and supersededBy to the newer document, re-signs the verification record and emits `document.superseded.v1`.
     */
    post: operations['supersedeDocument'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/v1/documents/{documentId}/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke an issued document (services)
     * @description Service tokens with scope documents:internal, acting for the tenant in X-Acting-Tenant. Sets the status to revoked with the reason (e.g. a clarification letter withdrawn as issued in error, spec 07a), re-signs the verification record and emits `document.revoked.v1`; the verify page then shows the document revoked.
     */
    post: operations['revokeDocument'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Sets allowed content types and the size limit
     * @enum {string}
     */
    UploadPurpose:
      | 'roster-import'
      | 'declaration-attachment'
      | 'clarification-attachment'
      | 'action-response'
      | 'access-representation';
    /** @enum {string} */
    UploadState: 'awaiting-upload' | 'clean' | 'infected' | 'rejected' | 'expired' | 'deleted';
    /**
     * @description Why a rejected upload was refused: `type` the bytes are not the declared type; `encoding` a CSV that is not UTF-8 text (save it as CSV UTF-8); `size` over the limit or not the declared size; `missing` nothing was uploaded; `timeout` the checks did not finish
     * @enum {string}
     */
    UploadRejection: 'type' | 'encoding' | 'size' | 'missing' | 'timeout';
    CreateUpload: {
      purpose: components['schemas']['UploadPurpose'];
      /**
       * @description One of the purpose's types; the PUT to uploadUrl must send it as Content-Type
       * @example text/csv
       * @example application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
       */
      contentType: string;
      /** @description Bytes; within the purpose's limit. The PUT must send exactly this many bytes */
      declaredSize: number;
      /** @description Display only; never used as an object key */
      fileName?: string;
    };
    UploadReservation: {
      /** Format: uuid */
      id: string;
      /**
       * Format: uri
       * @description Presigned PUT; send the raw bytes with the declared Content-Type and size before expiresAt
       */
      uploadUrl: string;
      /** Format: date-time */
      expiresAt: string;
      maxSize: number;
    };
    Upload: {
      /** Format: uuid */
      id: string;
      purpose: components['schemas']['UploadPurpose'];
      state: components['schemas']['UploadState'];
      rejection: components['schemas']['UploadRejection'] | null;
      /** @description Declared type; detectedType is set after completion */
      contentType: string;
      detectedType: string | null;
      declaredSize: number;
      size: number | null;
      /** @description Hex digest, set when clean */
      sha256: string | null;
      fileName: string | null;
      /** Format: date-time */
      createdAt: string;
      completedAt: string | null;
    };
    UploadDownload: {
      /** Format: uuid */
      id: string;
      purpose: components['schemas']['UploadPurpose'];
      /** @constant */
      state: 'clean';
      /** Format: uri */
      downloadUrl: string;
      /** Format: date-time */
      expiresAt: string;
      sha256: string;
      size: number;
      /** @description As given at createUpload; display only */
      fileName: string | null;
      /** @description Sniffed content type, e.g. text/csv or the XLSX type */
      detectedType: string;
    };
    /**
     * @description Document types with a template; later specs add theirs
     * @enum {string}
     */
    DocumentType:
      | 'acknowledgement-slip'
      | 'clarification-letter'
      | 'decision-letter'
      | 'notice-to-comply'
      | 'warning'
      | 'salary-stoppage'
      | 'disciplinary-referral'
      | 'referral-package'
      | 'access-package'
      | 'access-nil-letter'
      | 'certified-copy'
      | 'form-m'
      | 'compliance-report-receipt'
      | 'ncr';
    /**
     * @description What the public verify page shows: public (content), restricted (reference, type, Commission, date), confidential (validity only). Fixed by the document type's template
     * @enum {string}
     */
    DisclosureLevel: 'public' | 'restricted' | 'confidential';
    /** @enum {string} */
    DocumentStatus: 'valid' | 'superseded' | 'revoked' | 'expired';
    IssueDocument: {
      type: components['schemas']['DocumentType'];
      templateVersion: number;
      /**
       * @description The record the document is about; one document per type and subject. Issuing again returns it
       * @example declaration-version:0192f0c4-8a51-7cc2-9d1e-3b3f2a7e4c10
       */
      subjectRef: string;
      /** @description The only person who may download the document: the declarant, the applicant or the law-enforcement officer (their token carries it as `person_id`); null for none. Required for access-package, access-nil-letter and certified-copy; for a letter of the review service, the person its record names (none for an officer who never onboarded); null for a referral-package, a form-m, a compliance-report-receipt and an ncr */
      subjectPersonId: string | null;
      watermark?: components['schemas']['Watermark'];
      /** @description Days from issue during which the subject person may download the document; afterwards a download is refused with 410 `download-window-closed`. None: no window. Required for access-package and access-nil-letter */
      downloadWindowDays?: number;
      /** @description Token subjects (`sub`) of the issuing Commission's staff who may download the document besides its subject person, with a token of that Commission, within the same window and audited the same way: the access officer who recorded an in-person self-access application, to print the certified copy they hand over. None: the subject person only */
      additionalDownloaders?: string[];
      /** @description The template's payload: the schema named after `type`, or for a pulled type the record it is pulled for (`clarificationId`, `determinationId`, `actionId` or `referralId`) */
      payload:
        | components['schemas']['AcknowledgementSlipPayload']
        | components['schemas']['ClarificationLetterSource']
        | components['schemas']['DecisionLetterSource']
        | components['schemas']['ActionLetterSource']
        | components['schemas']['ReferralPackageSource']
        | components['schemas']['AccessPackagePayload']
        | components['schemas']['AccessNilLetterPayload']
        | components['schemas']['CertifiedCopyPayload']
        | components['schemas']['FormMPayload']
        | components['schemas']['ComplianceReportReceiptPayload']
        | components['schemas']['NcrPayload'];
    };
    /** @description A clarification-letter's payload: the clarification whose letter this is; the fields the template renders are pulled from the review service's letter payload endpoint */
    ClarificationLetterSource: {
      /** Format: uuid */
      clarificationId: string;
    };
    /** @description A decision-letter's payload: the approved determination whose letter this is; the fields are pulled from the review service (internalGetDeterminationLetterPayload) */
    DecisionLetterSource: {
      /** Format: uuid */
      determinationId: string;
    };
    /** @description The payload of a step letter (notice-to-comply, warning, salary-stoppage, disciplinary-referral): the approved administrative action whose letter this is; the fields are pulled from the review service (internalGetActionLetterPayload) */
    ActionLetterSource: {
      /** Format: uuid */
      actionId: string;
    };
    /** @description A referral-package's payload: the approved referral whose evidence package this is; the cover sheet, manifest and evidence are pulled from the review service (internalGetReferralPackagePayload) */
    ReferralPackageSource: {
      /** Format: uuid */
      referralId: string;
    };
    SupersedeDocument: {
      /**
       * Format: uuid
       * @description The newer document of the same type and tenant
       */
      supersededBy: string;
    };
    /**
     * @description Why the document is revoked, a category the verify page may show: issued-in-error (e.g. a clarification letter withdrawn as issued in error, spec 07a), withdrawn or other
     * @enum {string}
     */
    RevocationReason: 'issued-in-error' | 'withdrawn' | 'other';
    RevokeDocument: {
      reason: components['schemas']['RevocationReason'];
    };
    IssuedDocument: {
      /** Format: uuid */
      id: string;
      type: components['schemas']['DocumentType'];
      templateVersion: number;
      disclosureLevel: components['schemas']['DisclosureLevel'];
      issuerTenant: string;
      subjectRef: string;
      /**
       * @description Printed under the QR code
       * @example ADL-7Q4K-M2XR-9HTC-2B7F-Q3ZD-9KMV-8P
       */
      verificationId: string;
      /**
       * Format: uri
       * @description The QR code's payload: the document's verify page
       */
      verifyUrl: string;
      sha256: string;
      status: components['schemas']['DocumentStatus'];
      supersededBy: string | null;
      /** Format: date-time */
      issuedAt: string;
      /** @description End of the download window; null when the document has none */
      downloadExpiresAt: string | null;
    };
    DocumentDownload: {
      /**
       * Format: uri
       * @description Presigned GET of the signed PDF
       */
      downloadUrl: string;
      /** Format: date-time */
      expiresAt: string;
      sha256: string;
    };
    /** @description Printed across every page as `Issued to <recipientName> · <reference> · <date>` (ADR-010 §6), so a leaked copy traces to its recipient. Required for access-package and access-nil-letter */
    Watermark: {
      recipientName: string;
      /** @example ARQ-PSC-2026-0000012-H */
      reference: string;
      /** Format: date */
      date: string;
    };
    CommissionRef: {
      slug: string;
      issuerCode: string;
      name: string;
    };
    /** @description Payload of acknowledgement-slip v1: what the declarations service's acknowledgement payload endpoint returns for a submitted version */
    AcknowledgementSlipPayload: {
      declarantName: string;
      commissionName: string;
      issuerCode: string;
      /** @enum {string} */
      declarationType: 'initial' | 'biennial' | 'final';
      /** Format: date */
      statementDate: string;
      dueDate: string | null;
      /** @description Declaration reference number (ADR-011), e.g. DCB-PSC-2027-0000001-1 */
      reference: string;
      version: number;
      /** Format: date-time */
      submittedAt: string;
      late: boolean;
      statementCount: number;
      itemCount: number;
    };
    /** @description Payload of access-package v1: the declarations service's scoped disclosure for the grant, the clarifications disclosed with it, and what the grant decided */
    AccessPackagePayload: {
      disclosure: {
        /** @constant */
        schemaVersion: 'disclosure.v1';
        /**
         * @description The access request (ARQ) or law-enforcement request (LEA) reference
         * @example ARQ-PSC-2026-0000012-H
         */
        grantReference: string;
        personName: string;
        commission: components['schemas']['CommissionRef'];
        versions: {
          reference: string;
          version: number;
          /** @enum {string} */
          type: 'initial' | 'biennial' | 'final';
          /** Format: date */
          statementDate: string;
          /** Format: date-time */
          submittedAt: string;
          content: components['schemas']['DisclosedDeclaration'];
        }[];
      };
      /**
       * @description act-s36-1: an access request (Form K); act-s36-2: a law-enforcement request
       * @enum {string}
       */
      legalBasis: 'act-s36-1' | 'act-s36-2';
      recipient: {
        name: string;
        organisation: string | null;
      };
      /** Format: date-time */
      grantedAt: string;
      scope: {
        years: number[];
        includeSpouses: boolean;
        includeChildren: boolean;
        sections: ('bio' | 'income' | 'assets' | 'liabilities' | 'other')[];
        includeClarifications: boolean;
      };
      /** @description The clarifications of the disclosed declarations, as the review service disclosed them for the grant (oldest issued first; empty when none was issued in the scope); null when the grant does not include clarifications */
      clarifications:
        | {
            declarationReference: string;
            reference: string;
            /** @enum {string} */
            status: 'issued' | 'overdue' | 'responded' | 'resolved';
            /** Format: date-time */
            issuedAt: string;
            /** Format: date-time */
            dueAt: string;
            respondedAt: string | null;
            responseLate: boolean;
            resolvedAt: string | null;
            items: {
              label: string;
              requirementLabel: string;
              text: string;
              response: {
                text: string;
                attachmentNames: string[];
              } | null;
            }[];
          }[]
        | null;
    };
    /** @description Payload of access-nil-letter v1: a grant whose scope holds no declaration at the Commission, and whom the letter saying so is issued to */
    AccessNilLetterPayload: {
      /**
       * @description The access request (ARQ) or law-enforcement request (LEA) reference
       * @example ARQ-PSC-2026-0000012-H
       */
      grantReference: string;
      commission: components['schemas']['CommissionRef'];
      /** @description The declarant the request is about, as the Commission identified them */
      declarantName: string;
      /**
       * @description act-s36-1: an access request (Form K); act-s36-2: a law-enforcement request
       * @enum {string}
       */
      legalBasis: 'act-s36-1' | 'act-s36-2';
      recipient: {
        name: string;
        organisation: string | null;
      };
      /** Format: date-time */
      grantedAt: string;
      scope: {
        years: number[];
        includeSpouses: boolean;
        includeChildren: boolean;
        sections: ('bio' | 'income' | 'assets' | 'liabilities' | 'other')[];
        includeClarifications: boolean;
      };
    };
    /** @description Payload of certified-copy v1: the declarations service's full document of a submitted version (FullVersionDocument without its identifiers and hash) */
    CertifiedCopyPayload: {
      commission: components['schemas']['CommissionRef'];
      declarantName: string;
      /** @description Declaration reference number (ADR-011), e.g. DCB-PSC-2027-0000001-1 */
      reference: string;
      version: number;
      /** @enum {string} */
      type: 'initial' | 'biennial' | 'final';
      /** Format: date */
      statementDate: string;
      /** Format: date-time */
      submittedAt: string;
      document: components['schemas']['DeclarationV1'];
    };
    /** @description Payload of form-m v1: the submitted `form-m.v1` document as filed (FormMV1), with its RPT reference in `meta.reference`. Sent by the reporting service; the template prints every part of the prescribed form */
    FormMPayload: {
      /** @constant */
      schemaVersion: 'form-m.v1';
      partI: {
        commissionName: string;
        issuerCode: string;
        contactDetails: string;
        physicalAddress: string;
        /** Format: email */
        emailAddress: string;
        period: {
          /** Format: date */
          from: string;
          /** Format: date */
          to: string;
          financialYearStart: number;
        };
      };
      partII: {
        initial: components['schemas']['FormMDeclarationSection'];
        biennial: components['schemas']['FormMDeclarationSection'] & {
          noCycleInPeriod?: boolean;
        };
        final: components['schemas']['FormMDeclarationSection'];
        clarifications: {
          items: {
            name: string;
            designation: string;
            identifier: string;
            natureInGeneralTerms: string;
            /** @enum {string} */
            statusOfCompliance: 'responded' | 'resolved' | 'pending' | 'overdue' | 'withdrawn';
            clarificationReference?: string;
          }[];
        };
        accessRequests: {
          received: number;
          granted: number;
          declined: number;
          declineReasons: {
            /** @enum {string} */
            reason:
              | 'public-interest'
              | 'prejudice-proceeding'
              | 'frivolous-vexatious'
              | 'not-objectives'
              | 'other';
            count: number;
          }[];
          dataUnavailable: boolean;
        };
        complaints: {
          registerMaintained: boolean | null;
          items: {
            name: string;
            designation: string;
            identifier: string;
            nature: string;
            status: string;
          }[];
        };
      };
      partIII: {
        compiledBy: components['schemas']['FormMSignatory'];
        confirmedBy: components['schemas']['FormMSignatory'];
      };
      meta: {
        /** Format: date-time */
        compiledAt?: string;
        reference: string;
        /** @enum {string} */
        source?: 'hosted' | 'federated';
      };
    };
    /** @description Payload of compliance-report-receipt v1: the submitted report's RPT reference, the SHA-256 of its form-m.v1 document as received, the time of receipt, the Commission and the financial year with its due date and whether the report was late. Sent by the reporting service */
    ComplianceReportReceiptPayload: {
      reference: string;
      sha256: string;
      /** Format: date-time */
      submittedAt: string;
      commissionName: string;
      issuerCode: string;
      financialYear: string;
      /** Format: date */
      dueDate: string;
      late: boolean;
      /** @enum {string} */
      source: 'hosted' | 'federated';
    };
    /** @description Payload of ncr v1: the approved national consolidated report's NCR reference, financial year, build time and reports included, the aggregates reporting built (`reporting`, `national` and `byCommission`; counts and rates only), the narrative sections, the author and the approver. Sent by the reporting service */
    NcrPayload: {
      reference: string;
      financialYear: string;
      /** Format: date-time */
      builtAt: string;
      reportsIncluded: number;
      aggregates: {
        fy: number;
        reporting: {
          commissions: number;
          reported: number;
          onTime: number;
          late: number;
          notReported: number;
          rate: number | null;
        };
        national: {
          initial: {
            expected: number;
            declared: number;
            notDeclared: number;
            rate: number | null;
          };
          biennial: {
            expected: number;
            declared: number;
            notDeclared: number;
            rate: number | null;
          };
          final: {
            expected: number;
            declared: number;
            notDeclared: number;
            rate: number | null;
          };
          all: {
            expected: number;
            declared: number;
            notDeclared: number;
            rate: number | null;
          };
          clarifications: number;
          accessRequests: {
            received: number;
            granted: number;
            declined: number;
          };
        };
        byCommission: {
          [key: string]: {
            name: string;
            /** @enum {string} */
            status: 'not-reported' | 'submitted-on-time' | 'submitted-late';
            reportId: string | null;
            reference: string | null;
            submittedAt: string | null;
            initial: {
              expected: number;
              declared: number;
              notDeclared: number;
              rate: number | null;
            } | null;
            biennial: {
              expected: number;
              declared: number;
              notDeclared: number;
              rate: number | null;
              noCycleInPeriod: boolean;
            } | null;
            final: {
              expected: number;
              declared: number;
              notDeclared: number;
              rate: number | null;
            } | null;
            clarifications: number | null;
            accessRequests: {
              received: number;
              granted: number;
              declined: number;
            } | null;
          };
        };
      };
      narrative: {
        overview: string;
        findings: string;
        recommendations: string;
      };
      author: string;
      approver: string;
      /** Format: date-time */
      approvedAt: string;
    };
    FormMDeclarationSection: {
      expected: number;
      declared: number;
      notDeclared: number;
      nonFilers: {
        name: string;
        designation: string;
        identifier: string;
        /** Format: date */
        date: string;
        /** @enum {string} */
        actionTaken:
          | 'none'
          | 'notice-to-comply'
          | 'warning'
          | 'salary-stoppage'
          | 'disciplinary-referral'
          | 'referred-to-eacc';
        /** @enum {string} */
        complied: 'yes' | 'no' | 'pending';
        remarks?: string;
        /** Format: uuid */
        obligationId?: string;
      }[];
      noCycleInPeriod?: boolean;
    };
    FormMSignatory: {
      name: string | null;
      designation: string | null;
      date: string | null;
    };
    /** @description The declaration.v1 document cut to the granted scope: always schemaVersion, type, statementDate and attestation; with bio, officer (and spouses, children when included, without their national IDs, KRA PINs or dates of birth); with income, assets or liabilities, statements of the included persons holding only those parts (incomePeriod too with income); with other, otherInformation. An absent key was not granted */
    DisclosedDeclaration: {
      /** @constant */
      schemaVersion: 'declaration.v1';
      /** @enum {string} */
      type: 'initial' | 'biennial' | 'final';
      /** Format: date */
      statementDate: string;
      incomePeriod?: {
        /** Format: date */
        from: string;
        /** Format: date */
        to: string;
        /** @enum {string} */
        fromSource: 'declared' | 'assumed';
      };
      officer?: components['schemas']['DeclarationOfficer'];
      spouses?: {
        none: boolean;
        items: {
          /** Format: uuid */
          id: string;
          name: components['schemas']['PersonName'];
          /** @enum {string} */
          occupationSector?: 'public' | 'private' | 'not-employed' | 'unknown';
          separated: boolean;
          /** Format: date */
          separationDate?: string;
        }[];
      };
      children?: {
        none: boolean;
        items: {
          /** Format: uuid */
          id: string;
          name: components['schemas']['PersonName'];
          includedAtStatementDate: boolean;
        }[];
      };
      statements?: {
        personKey: string;
        personName: components['schemas']['PersonName'];
        /** Format: date */
        statementDate: string;
        incomePeriod: {
          /** Format: date */
          from: string;
          /** Format: date */
          to: string;
        };
        incomeNil?: boolean;
        income?: components['schemas']['DeclarationIncomeItem'][];
        assetsNil?: boolean;
        assets?: components['schemas']['DeclarationAssetItem'][];
        liabilitiesNil?: boolean;
        liabilities?: components['schemas']['DeclarationLiabilityItem'][];
        knowledgeLimitation?: string;
      }[];
      otherInformation?: components['schemas']['DeclarationOtherInformation'];
      attestation: {
        /** @constant */
        text: 'I solemnly declare that the information I have given in this declaration is, to the best of my knowledge, true and complete.';
        /** Format: date-time */
        declaredAt?: string;
        reference?: string;
      };
    };
    DeclarationV1: {
      /** @constant */
      schemaVersion: 'declaration.v1';
      /** @enum {string} */
      type: 'initial' | 'biennial' | 'final';
      /** Format: date */
      statementDate: string;
      incomePeriod: {
        /** Format: date */
        from: string;
        /** Format: date */
        to: string;
        /** @enum {string} */
        fromSource: 'declared' | 'assumed';
      };
      officer: components['schemas']['DeclarationOfficer'];
      spouses: components['schemas']['DeclarationSpouses'];
      children: components['schemas']['DeclarationChildren'];
      statements: {
        personKey: string;
        personName: components['schemas']['PersonName'];
        /** Format: date */
        statementDate: string;
        incomePeriod: {
          /** Format: date */
          from: string;
          /** Format: date */
          to: string;
        };
        incomeNil: boolean;
        income: components['schemas']['DeclarationIncomeItem'][];
        assetsNil: boolean;
        assets: components['schemas']['DeclarationAssetItem'][];
        liabilitiesNil: boolean;
        liabilities: components['schemas']['DeclarationLiabilityItem'][];
        knowledgeLimitation?: string;
      }[];
      otherInformation: components['schemas']['DeclarationOtherInformation'];
      attestation: {
        /** @constant */
        text: 'I solemnly declare that the information I have given in this declaration is, to the best of my knowledge, true and complete.';
        /** Format: date-time */
        declaredAt?: string;
        reference?: string;
      };
    };
    DeclarationOfficer: {
      name: components['schemas']['PersonName'];
      birth: {
        /** Format: date */
        date: string;
        place: string;
      };
      /** @enum {string} */
      maritalStatus: 'single' | 'married' | 'separated' | 'divorced' | 'widowed';
      maritalStatusChange?: {
        changed: boolean;
        explanation?: string;
      };
      address: {
        postal: string;
        physical: string;
      };
      employment: {
        designation: string;
        employer: string;
        /** @enum {string} */
        nature: 'permanent' | 'temporary' | 'contract' | 'other';
        natureOther?: string;
        responsibleCommission: string;
        personnelFileNumber?: string;
        jobGroup?: string;
        /** Format: date */
        appointmentDate?: string;
        workStation?: string;
      };
    };
    DeclarationSpouses: {
      none: boolean;
      items: {
        /** Format: uuid */
        id: string;
        name: components['schemas']['PersonName'];
        nationalId?: string;
        kraPin?: string;
        /** @enum {string} */
        occupationSector?: 'public' | 'private' | 'not-employed' | 'unknown';
        separated: boolean;
        /** Format: date */
        separationDate?: string;
      }[];
    };
    DeclarationChildren: {
      none: boolean;
      items: {
        /** Format: uuid */
        id: string;
        name: components['schemas']['PersonName'];
        /** Format: date */
        dateOfBirth: string;
        nationalId?: string;
        includedAtStatementDate: boolean;
      }[];
    };
    DeclarationOtherInformation: {
      materialChanges: {
        personKey?: string;
        /** Format: uuid */
        itemId?: string;
        itemDescription?: string;
        /** @enum {string} */
        kind:
          | 'value-change'
          | 'acquisition'
          | 'disposal'
          | 'new-source'
          | 'source-ended'
          | 'settled'
          | 'marital-status'
          | 'directorship'
          | 'membership';
        explanation: string;
      }[];
      registrableInterests: {
        directorships: {
          /** Format: uuid */
          id?: string;
          company: string;
          role: string;
          remunerated: boolean;
          change?: {
            changed: boolean;
            /** @enum {string} */
            kind?:
              | 'value-change'
              | 'acquisition'
              | 'disposal'
              | 'new-source'
              | 'source-ended'
              | 'settled';
            explanation?: string;
          };
          source?: {
            /** @enum {string} */
            kind: 'kra' | 'ntsa' | 'brs' | 'ardhisasa' | 'document';
            /** Format: uuid */
            suggestionId: string;
            /** Format: uuid */
            verificationResultId?: string;
            /** Format: uuid */
            aiJobId?: string;
            /** Format: date-time */
            at: string;
          };
        }[];
        memberships: {
          entity: string;
          /** @enum {string} */
          kind: 'company' | 'partnership' | 'society' | 'club' | 'foundation' | 'trust' | 'other';
          change?: {
            changed: boolean;
            /** @enum {string} */
            kind?:
              | 'value-change'
              | 'acquisition'
              | 'disposal'
              | 'new-source'
              | 'source-ended'
              | 'settled';
            explanation?: string;
          };
        }[];
        dualCitizenship: {
          holds: boolean;
          country?: string;
          pendingApplication: boolean;
        };
        pendingCases: {
          forum: string;
          reference: string;
          nature: string;
        }[];
      };
      freeText: string;
    };
    DeclarationIncomeItem: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      type:
        | 'salary-emoluments'
        | 'allowances'
        | 'business'
        | 'rent'
        | 'dividends-interest'
        | 'pension'
        | 'farming'
        | 'consultancy'
        | 'other';
      description: string;
      amount: {
        kesCents: number;
        original?: {
          currency: string;
          minorUnits: number;
        };
      };
      location: {
        inKenya: boolean;
        county?: string;
        country?: string;
        detail?: string;
      };
      change: {
        changed: boolean;
        /** @enum {string} */
        kind?:
          'value-change' | 'acquisition' | 'disposal' | 'new-source' | 'source-ended' | 'settled';
        explanation?: string;
      };
      source?: {
        /** @enum {string} */
        kind: 'kra' | 'ntsa' | 'brs' | 'ardhisasa' | 'document';
        /** Format: uuid */
        suggestionId: string;
        /** Format: uuid */
        verificationResultId?: string;
        /** Format: uuid */
        aiJobId?: string;
        /** Format: date-time */
        at: string;
      };
      attachments?: {
        /** Format: uuid */
        attachmentId: string;
        /** Format: uuid */
        uploadId: string;
        fileName: string;
        sha256: string;
      }[];
    };
    DeclarationAssetItem: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      type:
        | 'land'
        | 'building'
        | 'vehicle'
        | 'securities'
        | 'shareholding'
        | 'bank-account'
        | 'cash'
        | 'receivable'
        | 'other';
      description: string;
      details?: {
        parcelNumber?: string;
        size?: string;
        registration?: string;
        makeModel?: string;
        issuer?: string;
        quantityOrPercent?: string;
        institution?: string;
        accountType?: string;
        debtor?: string;
      };
      value: {
        kesCents: number;
        original?: {
          currency: string;
          minorUnits: number;
        };
      };
      location: {
        inKenya: boolean;
        county?: string;
        country?: string;
        detail?: string;
      };
      joint: {
        isJoint: boolean;
        sharePercent?: number;
        coOwner?: string;
      };
      change: {
        changed: boolean;
        /** @enum {string} */
        kind?:
          'value-change' | 'acquisition' | 'disposal' | 'new-source' | 'source-ended' | 'settled';
        explanation?: string;
      };
      source?: {
        /** @enum {string} */
        kind: 'kra' | 'ntsa' | 'brs' | 'ardhisasa' | 'document';
        /** Format: uuid */
        suggestionId: string;
        /** Format: uuid */
        verificationResultId?: string;
        /** Format: uuid */
        aiJobId?: string;
        /** Format: date-time */
        at: string;
      };
      attachments?: {
        /** Format: uuid */
        attachmentId: string;
        /** Format: uuid */
        uploadId: string;
        fileName: string;
        sha256: string;
      }[];
    };
    DeclarationLiabilityItem: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      type: 'mortgage' | 'loan' | 'guarantee' | 'other';
      description: string;
      creditor: string;
      outstanding: {
        kesCents: number;
        original?: {
          currency: string;
          minorUnits: number;
        };
      };
      location: {
        inKenya: boolean;
        county?: string;
        country?: string;
        detail?: string;
      };
      change: {
        changed: boolean;
        /** @enum {string} */
        kind?:
          'value-change' | 'acquisition' | 'disposal' | 'new-source' | 'source-ended' | 'settled';
        explanation?: string;
      };
      source?: {
        /** @enum {string} */
        kind: 'kra' | 'ntsa' | 'brs' | 'ardhisasa' | 'document';
        /** Format: uuid */
        suggestionId: string;
        /** Format: uuid */
        verificationResultId?: string;
        /** Format: uuid */
        aiJobId?: string;
        /** Format: date-time */
        at: string;
      };
      attachments?: {
        /** Format: uuid */
        attachmentId: string;
        /** Format: uuid */
        uploadId: string;
        fileName: string;
        sha256: string;
      }[];
    };
    PersonName: {
      surname: string;
      firstName: string;
      otherNames?: string;
    };
    InternalUpload: {
      /** Format: uuid */
      id: string;
      purpose: components['schemas']['UploadPurpose'];
      state: components['schemas']['UploadState'];
      rejection: components['schemas']['UploadRejection'] | null;
      /** @description Declared type; detectedType is set after completion */
      contentType: string;
      detectedType: string | null;
      declaredSize: number;
      size: number | null;
      /** @description Hex digest, set when clean */
      sha256: string | null;
      fileName: string | null;
      /** Format: date-time */
      createdAt: string;
      completedAt: string | null;
      /** @description Token subject (`sub`) of the caller who reserved the upload */
      uploadedBy: string;
      /** @description When the owning service linked it to its record; null while unlinked */
      linkedAt: string | null;
    };
    ProblemDetails: {
      type: string;
      title: string;
      status: number;
      /**
       * @description Machine-readable cause, from the platform registry; clients map it to copy and never show `title` or `detail`
       * @enum {string}
       */
      code?:
        | 'database-unavailable'
        | 'rate-limit-exceeded'
        | 'no-match'
        | 'already-onboarded'
        | 'no-roster'
        | 'otp-invalid'
        | 'otp-expired'
        | 'resend-cooldown'
        | 'otp-send-failed'
        | 'wrong-step'
        | 'session-expired'
        | 'iprs-unavailable'
        | 'identity-unavailable'
        | 'email-in-use'
        | 'identity-mismatch'
        | 'step-up-required'
        | 'incomplete'
        | 'before-statement-date'
        | 'amendment-window-closed'
        | 'not-a-draft'
        | 'not-submitted'
        | 'obligation-cancelled'
        | 'acknowledgement-issued'
        | 'acknowledgement-in-progress'
        | 'consent-required'
        | 'no-id'
        | 'not-new'
        | 'no-applicant-record'
        | 'request-decided'
        | 'request-closed'
        | 'officer-resolved'
        | 'not-under-decision'
        | 'not-pending-verification'
        | 'lea-account-inactive'
        | 'declarant-notified'
        | 'representations-closed'
        | 'download-window-closed'
        | 'scope-exceeds-request'
        | 'grounds-required'
        | 'separation-of-duties'
        | 'report-submitted'
        | 'report-compiling'
        | 'preview-not-available'
        | 'not-reviewed'
        | 'invalid-remarks'
        | 'invalid-document'
        | 'inconsistent-document'
        | 'tenant-mismatch'
        | 'ncr-approved'
        | 'no-submitted-reports'
        | 'icms-push-failed';
      detail?: string;
      instance?: string;
      /** @description Field-level errors; `path` is the dotted request field */
      errors?: {
        path: string;
        message: string;
      }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  createUpload: {
    parameters: {
      query?: never;
      header: {
        /** @description Client-generated UUID, unique per logical request; reuse on retry */
        'Idempotency-Key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUpload'];
      };
    };
    responses: {
      /** @description Upload reserved; PUT the bytes to uploadUrl before expiresAt */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UploadReservation'];
        };
      };
      /** @description Request failed validation, or the type or size is not the purpose's */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Your roles do not allow uploads for this purpose */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Idempotency-Key reused with a different request body */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  getUpload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The upload */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Upload'];
        };
      };
      /** @description Not found, or not visible to the caller */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  completeUpload: {
    parameters: {
      query?: never;
      header: {
        /** @description Client-generated UUID, unique per logical request; reuse on retry */
        'Idempotency-Key': string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Final state after scanning */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Upload'];
        };
      };
      /** @description Not found, or not visible to the caller */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Problem type `upload-completed` (already clean, infected or rejected), `upload-expired`, or `upload-completing` (another request is completing it). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Idempotency-Key reused with a different request body */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Problem type `upload-check-unavailable`: storage or the scanner failed; nothing changed, retry. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  getInternalUpload: {
    parameters: {
      query?: never;
      header: {
        /** @description Tenant the calling service acts for; the resource must belong to it */
        'X-Acting-Tenant': string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The upload */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InternalUpload'];
        };
      };
      /** @description X-Acting-Tenant is missing or not a tenant key */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Requires a service token with scope documents:internal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not found, or not the acting tenant's upload */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  getUploadDownload: {
    parameters: {
      query?: never;
      header: {
        /** @description Tenant the calling service acts for; the resource must belong to it */
        'X-Acting-Tenant': string;
        /** @description The subject the service reads for (a reviewer opening an attachment, or the declarant whose response attaches it); recorded as the audit event's on-behalf-of, grants nothing (ADR-013 §8.6) */
        'X-Acting-Subject'?: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Download URL valid for a few minutes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UploadDownload'];
        };
      };
      /** @description X-Acting-Tenant is missing or not a tenant key */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Requires a service token with scope documents:internal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not found, or not the acting tenant's upload */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Problem type `upload-not-clean`: the upload is not clean */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  markUploadLinked: {
    parameters: {
      query?: never;
      header: {
        /** @description Tenant the calling service acts for; the resource must belong to it */
        'X-Acting-Tenant': string;
        /** @description Optional. Client-generated UUID, unique per logical request; reuse on retry and the stored answer is replayed instead of acting twice */
        'Idempotency-Key'?: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Link recorded */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description X-Acting-Tenant is missing or not a tenant key */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Requires a service token with scope documents:internal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not found, or not the acting tenant's upload */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Problem type `upload-not-clean`: the upload is not clean */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Idempotency-Key reused with a different request body */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  markUploadUnlinked: {
    parameters: {
      query?: never;
      header: {
        /** @description Tenant the calling service acts for; the resource must belong to it */
        'X-Acting-Tenant': string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Link taken back */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description X-Acting-Tenant is missing or not a tenant key */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Requires a service token with scope documents:internal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not found, or not the acting tenant's upload */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  getDocument: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        documentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssuedDocument'];
        };
      };
      /** @description Not found, or not visible to the caller */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  getDocumentDownload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        documentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Download URL valid for five minutes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentDownload'];
        };
      };
      /** @description Not found, or not visible to the caller */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Problem type `download-window-closed`: the download window has ended */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  issueDocument: {
    parameters: {
      query?: never;
      header: {
        /** @description Tenant the calling service acts for; the resource must belong to it */
        'X-Acting-Tenant': string;
        /** @description Optional. Client-generated UUID, unique per logical request; reuse on retry and the stored answer is replayed instead of acting twice */
        'Idempotency-Key'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IssueDocument'];
      };
    };
    responses: {
      /** @description Issued for this subject already; the document issued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssuedDocument'];
        };
      };
      /** @description Issued */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssuedDocument'];
        };
      };
      /** @description Request failed validation, the payload (or the one pulled) is not the template's, the request lacks what the type requires, the subject person is not the pulled record's, or the review service holds no such record with a document to issue for the tenant */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Requires a service token with scope documents:internal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Idempotency-Key reused with a different request body */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Problem type `renderer-unavailable`, `signer-unavailable`, `storage-unavailable` or `review-unavailable`: nothing was issued; retry */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  internalGetDocument: {
    parameters: {
      query?: never;
      header: {
        /** @description Tenant the calling service acts for; the resource must belong to it */
        'X-Acting-Tenant': string;
      };
      path: {
        documentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssuedDocument'];
        };
      };
      /** @description X-Acting-Tenant is missing or not a tenant key */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Requires a service token with scope documents:internal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not found, or not the acting tenant's document */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  internalGetDocumentDownload: {
    parameters: {
      query?: never;
      header: {
        /** @description Tenant the calling service acts for; the resource must belong to it */
        'X-Acting-Tenant': string;
        /** @description The staff subject the service reads for (a reviewer downloading a clarification letter); recorded as the audit event's on-behalf-of, grants nothing (ADR-013 §8.6) */
        'X-Acting-Subject'?: string;
      };
      path: {
        documentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Download URL valid for five minutes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentDownload'];
        };
      };
      /** @description X-Acting-Tenant is missing or not a tenant key */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Requires a service token with scope documents:internal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not found, or not the acting tenant's document */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  supersedeDocument: {
    parameters: {
      query?: never;
      header: {
        /** @description Tenant the calling service acts for; the resource must belong to it */
        'X-Acting-Tenant': string;
        /** @description Optional. Client-generated UUID, unique per logical request; reuse on retry and the stored answer is replayed instead of acting twice */
        'Idempotency-Key'?: string;
      };
      path: {
        documentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SupersedeDocument'];
      };
    };
    responses: {
      /** @description Superseded */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssuedDocument'];
        };
      };
      /** @description X-Acting-Tenant is missing or not a tenant key */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Requires a service token with scope documents:internal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not found, or not the acting tenant's document */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Problem type `document-not-valid` (superseded, revoked or expired already) or `superseding-document-invalid` (the newer document is not a valid document of the same type) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Idempotency-Key reused with a different request body */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Problem type `signer-unavailable`: nothing changed; retry */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  revokeDocument: {
    parameters: {
      query?: never;
      header: {
        /** @description Tenant the calling service acts for; the resource must belong to it */
        'X-Acting-Tenant': string;
        /** @description Optional. Client-generated UUID, unique per logical request; reuse on retry and the stored answer is replayed instead of acting twice */
        'Idempotency-Key'?: string;
      };
      path: {
        documentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RevokeDocument'];
      };
    };
    responses: {
      /** @description Revoked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssuedDocument'];
        };
      };
      /** @description X-Acting-Tenant is missing or not a tenant key */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Requires a service token with scope documents:internal */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Not found, or not the acting tenant's document */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Problem type `document-revoked` (revoked already: a caller may treat its revoke as done) or `document-not-valid` (superseded or expired: not revoked) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Idempotency-Key reused with a different request body */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Problem type `signer-unavailable`: nothing changed; retry */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
}
