[SERVICE]
    Daemon          off
    Flush           1
    Log_Level       info
    Parsers_File    parsers.conf

[INPUT]
    Name            systemd
    Tag             adili.apps
    Systemd_Filter  _SYSTEMD_UNIT=adili-apps.service
    Read_From_Tail  On
    DB              /var/lib/fluent-bit/journal.db
    Mem_Buf_Limit   20MB

[FILTER]
    Name            modify
    Match           *
    Add             service.name adili-apps

[OUTPUT]
    Name            opentelemetry
    Match           *
    Host            signoz-ingester
    Port            4318
    Logs_uri        /v1/logs
    logs_body_key   MESSAGE
    Tls             Off
