// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 06ce6607cf5aaad3387c5408db2d3bd64f5ceafb42a19045abce63298d38f5a1

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from 'react';

export type ThemeName = 'adili';

export const themeNames: ThemeName[] = ['adili'];

export type KcEnvName = 'ADILI_CONSOLE_URL' | 'ADILI_PORTAL_URL';

export const kcEnvNames: KcEnvName[] = ['ADILI_CONSOLE_URL', 'ADILI_PORTAL_URL'];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  ADILI_CONSOLE_URL: 'http://localhost:3020',
  ADILI_PORTAL_URL: 'http://localhost:3010',
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import('./login/KcContext').KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}

export const KcLoginPage = lazy(() => import('./login/KcPage'));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
  const { kcContext, fallback } = props;
  return (
    <Suspense fallback={fallback}>
      {(() => {
        switch (kcContext.themeType) {
          case 'login':
            return <KcLoginPage kcContext={kcContext} />;
        }
      })()}
    </Suspense>
  );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;
