// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 1d843b4987d56d3045e0e9f509379ad5f54bd2c8c96e0fc0d8e20624c4c4cac5


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "adili";

export const themeNames: ThemeName[] = ["adili"];

export type KcEnvName = "ADILI_CONSOLE_URL";

export const kcEnvNames: KcEnvName[] = ["ADILI_CONSOLE_URL"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "ADILI_CONSOLE_URL": "http://localhost:3020"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint. 
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL
