import type { components } from './api.gen';

type Schemas = components['schemas'];

export type Assignee = Schemas['Assignee'];
export type CaseDetail = Schemas['CaseDetail'];
export type CaseListItem = Schemas['CaseListItem'];
export type CaseStatus = Schemas['CaseStatus'];
export type Clarification = Schemas['Clarification'];
export type Determination = Schemas['Determination'];
export type DeterminationInput = Schemas['DeterminationInput'];
export type DeterminationOutcome = Schemas['DeterminationOutcome'];
export type ApprovalItem = Schemas['ApprovalItem'];
export type ApprovalKind = Schemas['ApprovalKind'];
export type LetterDownload = Schemas['LetterDownload'];
export type Flag = Schemas['Flag'];
export type Note = Schemas['Note'];
export type Severity = Schemas['Severity'];
export type ClarificationStatus = Schemas['ClarificationStatus'];
export type CopilotFeedbackInput = Schemas['CopilotFeedbackInput'];
export type CopilotStatus = Schemas['CopilotStatus'];
export type CopilotView = Schemas['CopilotView'];
export type Requirement = Schemas['Requirement'];
export type TimelineEntry = Schemas['TimelineEntry'];
export type RegistrySystem = Schemas['RegistrySystem'];
export type RegistryCheckStatus = Schemas['RegistryCheckStatus'];
export type RegistrySummary = Schemas['RegistrySummary'];
export type RegistryView = Schemas['RegistryView'];
export type CopilotDraft = Schemas['CopilotDraft'];
export type CopilotDraftInput = Schemas['CopilotDraftInput'];
export type VersionComparison = Schemas['VersionComparison'];
