import type { z } from 'zod';

import {
  attachmentLinkSchema,
  completenessIssueSchema,
  declarationAttachmentSchema,
  completenessSchema,
  declarationListItemSchema,
  declarationSchema,
  declarationStatusSchema,
  declarationSummarySchema,
  notIncludedSchema,
  sectionContentsSchema,
  sectionEnvelopeSchema,
  sectionKeySchema,
  sectionSaveResultSchema,
} from './drafts/representation.js';
import {
  corpusImportResultSchema,
  corpusPassageSchema,
  helpArticleInputSchema,
  helpArticleSchema,
  helpLanguageSchema,
  helpPassageSchema,
  helpTagSchema,
} from './help/representation.js';
import {
  cancelReasonSchema,
  commissionRefSchema,
  commissionSummarySchema,
  declarationProgressSchema,
  myObligationsSchema,
  nationalSummarySchema,
  obligationDetailSchema,
  obligationListItemSchema,
  obligationPageSchema,
  obligationSchema,
  obligationStatusSchema,
  obligationTypeSchema,
  progressCountsSchema,
  reportingEntityRefSchema,
  declarantRefSchema,
  reminderChannelSchema,
  reminderOutcomeSchema,
  reminderSchema,
  statusCountsSchema,
  summaryCycleSchema,
} from './obligations/representation.js';

/**
 * Named schemas of the declarations service's OpenAPI document (`#/components/schemas/<name>`),
 * which is exported to packages/schemas/internal/declarations.yaml by `pnpm contracts`.
 */
export const OPENAPI_SCHEMAS: Record<string, z.ZodType> = {
  ObligationType: obligationTypeSchema,
  ObligationStatus: obligationStatusSchema,
  CancelReason: cancelReasonSchema,
  ReminderOutcome: reminderOutcomeSchema,
  ReminderChannel: reminderChannelSchema,
  CommissionRef: commissionRefSchema,
  Obligation: obligationSchema,
  Reminder: reminderSchema,
  DeclarantRef: declarantRefSchema,
  ObligationDetail: obligationDetailSchema,
  MyObligations: myObligationsSchema,
  ObligationListItem: obligationListItemSchema,
  ObligationPage: obligationPageSchema,
  StatusCounts: statusCountsSchema,
  SummaryCycle: summaryCycleSchema,
  CommissionSummary: commissionSummarySchema,
  NationalSummary: nationalSummarySchema,
  ProgressCounts: progressCountsSchema,
  ReportingEntityRef: reportingEntityRefSchema,
  DeclarationProgress: declarationProgressSchema,
  SectionKey: sectionKeySchema,
  Completeness: completenessSchema,
  DeclarationStatus: declarationStatusSchema,
  Declaration: declarationSchema,
  SectionContents: sectionContentsSchema,
  CompletenessIssue: completenessIssueSchema,
  NotIncluded: notIncludedSchema,
  SectionEnvelope: sectionEnvelopeSchema,
  SectionSaveResult: sectionSaveResultSchema,
  AttachmentLink: attachmentLinkSchema,
  DeclarationAttachment: declarationAttachmentSchema,
  DeclarationSummary: declarationSummarySchema,
  DeclarationListItem: declarationListItemSchema,
  HelpLanguage: helpLanguageSchema,
  HelpTag: helpTagSchema,
  HelpPassage: helpPassageSchema,
  HelpArticleInput: helpArticleInputSchema,
  HelpArticle: helpArticleSchema,
  CorpusPassage: corpusPassageSchema,
  CorpusImportResult: corpusImportResultSchema,
};
