import type { z } from 'zod';

import {
  acknowledgementPayloadSchema,
  acknowledgementSlipSchema,
} from './acknowledgement/representation.js';
import {
  internalObligationDetailsSchema,
  internalObligationSchema,
  internalPersonObligationSchema,
  internalPersonVersionSchema,
  internalPreviousVersionSchema,
  internalVersionDocumentSchema,
} from './service-reads/representation.js';
import {
  attachmentLinkSchema,
  completenessIssueSchema,
  declarationAttachmentSchema,
  completenessSchema,
  declarationListItemSchema,
  declarationSchema,
  declarationStatusSchema,
  declarationSummarySchema,
  notIncludedSchema,
  sectionContentsSchema,
  sectionEnvelopeSchema,
  sectionKeySchema,
  sectionSaveResultSchema,
} from './drafts/representation.js';
import {
  corpusImportResultSchema,
  corpusPassageSchema,
  helpArticleInputSchema,
  helpArticleSchema,
  helpLanguageSchema,
  helpPassageSchema,
  helpTagSchema,
} from './help/representation.js';
import {
  cancelReasonSchema,
  commissionRefSchema,
  commissionSummarySchema,
  declarationProgressSchema,
  myObligationsSchema,
  nationalSummarySchema,
  obligationDetailSchema,
  obligationListItemSchema,
  obligationPageSchema,
  obligationSchema,
  obligationStatusSchema,
  obligationTypeSchema,
  progressCountsSchema,
  reportingEntityRefSchema,
  declarantRefSchema,
  reminderChannelSchema,
  reminderOutcomeSchema,
  reminderSchema,
  statusCountsSchema,
  summaryCycleSchema,
} from './obligations/representation.js';
import { declarationReferenceSchema } from './declaration/reference.js';
import {
  disclosedVersionSchema,
  disclosureCountsRequestSchema,
  disclosureCountsSchema,
  disclosureDocumentSchema,
  disclosureRequestSchema,
  disclosureYearCountsSchema,
  fullDocumentRequestSchema,
  disclosureSectionSchema,
  fullVersionDocumentSchema,
  grantReferenceSchema,
  legalBasisSchema,
} from './disclosure/representation.js';
import {
  acknowledgementSchema,
  acknowledgementStatusSchema,
  declarationVersionDetailSchema,
  declarationVersionSchema,
} from './declaration/representation.js';
import { submissionResultSchema, submitProblemSchema } from './submission/representation.js';
import {
  acceptSuggestionRequestSchema,
  dismissSuggestionRequestSchema,
  registryLookupRequestSchema,
  suggestionAcceptanceSchema,
  suggestionSchema,
  suggestionSetSchema,
  suggestionSourceSchema,
} from './suggestions/representation.js';

/**
 * Named schemas of the declarations service's OpenAPI document (`#/components/schemas/<name>`),
 * which is exported to packages/schemas/internal/declarations.yaml by `pnpm contracts`.
 */
export const OPENAPI_SCHEMAS: Record<string, z.ZodType> = {
  ObligationType: obligationTypeSchema,
  ObligationStatus: obligationStatusSchema,
  CancelReason: cancelReasonSchema,
  ReminderOutcome: reminderOutcomeSchema,
  ReminderChannel: reminderChannelSchema,
  CommissionRef: commissionRefSchema,
  Obligation: obligationSchema,
  Reminder: reminderSchema,
  DeclarantRef: declarantRefSchema,
  ObligationDetail: obligationDetailSchema,
  MyObligations: myObligationsSchema,
  ObligationListItem: obligationListItemSchema,
  ObligationPage: obligationPageSchema,
  StatusCounts: statusCountsSchema,
  SummaryCycle: summaryCycleSchema,
  CommissionSummary: commissionSummarySchema,
  NationalSummary: nationalSummarySchema,
  ProgressCounts: progressCountsSchema,
  ReportingEntityRef: reportingEntityRefSchema,
  DeclarationProgress: declarationProgressSchema,
  DeclarationReference: declarationReferenceSchema,
  SectionKey: sectionKeySchema,
  Completeness: completenessSchema,
  DeclarationStatus: declarationStatusSchema,
  Declaration: declarationSchema,
  SectionContents: sectionContentsSchema,
  CompletenessIssue: completenessIssueSchema,
  NotIncluded: notIncludedSchema,
  SectionEnvelope: sectionEnvelopeSchema,
  SectionSaveResult: sectionSaveResultSchema,
  AttachmentLink: attachmentLinkSchema,
  DeclarationAttachment: declarationAttachmentSchema,
  DeclarationSummary: declarationSummarySchema,
  DeclarationListItem: declarationListItemSchema,
  AcknowledgementStatus: acknowledgementStatusSchema,
  Acknowledgement: acknowledgementSchema,
  DeclarationVersion: declarationVersionSchema,
  DeclarationVersionDetail: declarationVersionDetailSchema,
  SubmissionResult: submissionResultSchema,
  SubmitProblem: submitProblemSchema,
  AcknowledgementSlip: acknowledgementSlipSchema,
  AcknowledgementPayload: acknowledgementPayloadSchema,
  DisclosureSection: disclosureSectionSchema,
  LegalBasis: legalBasisSchema,
  GrantReference: grantReferenceSchema,
  DisclosureRequest: disclosureRequestSchema,
  DisclosedVersion: disclosedVersionSchema,
  DisclosureDocument: disclosureDocumentSchema,
  DisclosureCountsRequest: disclosureCountsRequestSchema,
  DisclosureYearCounts: disclosureYearCountsSchema,
  DisclosureCounts: disclosureCountsSchema,
  FullDocumentRequest: fullDocumentRequestSchema,
  FullVersionDocument: fullVersionDocumentSchema,
  HelpLanguage: helpLanguageSchema,
  HelpTag: helpTagSchema,
  HelpPassage: helpPassageSchema,
  HelpArticleInput: helpArticleInputSchema,
  HelpArticle: helpArticleSchema,
  CorpusPassage: corpusPassageSchema,
  CorpusImportResult: corpusImportResultSchema,
  InternalVersionDocument: internalVersionDocumentSchema,
  InternalPersonVersion: internalPersonVersionSchema,
  InternalPreviousVersion: internalPreviousVersionSchema,
  InternalObligation: internalObligationSchema,
  InternalPersonObligation: internalPersonObligationSchema,
  InternalObligationDetails: internalObligationDetailsSchema,
  SuggestionSource: suggestionSourceSchema,
  Suggestion: suggestionSchema,
  SuggestionSet: suggestionSetSchema,
  RegistryLookupRequest: registryLookupRequestSchema,
  AcceptSuggestionRequest: acceptSuggestionRequestSchema,
  SuggestionAcceptance: suggestionAcceptanceSchema,
  DismissSuggestionRequest: dismissSuggestionRequestSchema,
};
