/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as VIndexRouteImport } from './routes/v.index'
import { Route as VVerificationIdRouteImport } from './routes/v.$verificationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const VIndexRoute = VIndexRouteImport.update({
  id: '/v/',
  path: '/v/',
  getParentRoute: () => rootRouteImport,
} as any)
const VVerificationIdRoute = VVerificationIdRouteImport.update({
  id: '/v/$verificationId',
  path: '/v/$verificationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/v/$verificationId': typeof VVerificationIdRoute
  '/v/': typeof VIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/v/$verificationId': typeof VVerificationIdRoute
  '/v': typeof VIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/v/$verificationId': typeof VVerificationIdRoute
  '/v/': typeof VIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/v/$verificationId' | '/v/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/v/$verificationId' | '/v'
  id: '__root__' | '/' | '/about' | '/v/$verificationId' | '/v/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  VVerificationIdRoute: typeof VVerificationIdRoute
  VIndexRoute: typeof VIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/': {
      id: '/v/'
      path: '/v'
      fullPath: '/v/'
      preLoaderRoute: typeof VIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$verificationId': {
      id: '/v/$verificationId'
      path: '/v/$verificationId'
      fullPath: '/v/$verificationId'
      preLoaderRoute: typeof VVerificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  VVerificationIdRoute: VVerificationIdRoute,
  VIndexRoute: VIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
