# Generated by Django 6.1.1 on 2026-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.CharField(max_length=60, unique=True)),
                ('county', models.CharField(max_length=50)),
                ('area_hectares', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tenure', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=10)),
                ('owner_id_number', models.CharField(db_index=True, max_length=10)),
                ('registered_on', models.DateField()),
            ],
            options={
                'ordering': ['parcel_number'],
            },
        ),
    ]
