/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render a template and send it by email or SMS
         * @description Synchronous with a 5-second budget. Callers use service tokens.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Delivery status of a message */
        get: operations["getMessage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Channel: "email" | "sms";
        /**
         * @description Registered templates; each declares its params
         * @enum {string}
         */
        TemplateId: "onboarding-otp-email" | "onboarding-otp-sms" | "login-otp-sms" | "login-otp-email" | "obligation-reminder-sms" | "obligation-reminder-email" | "acknowledgement-email" | "acknowledgement-sms" | "clarification-issued-email" | "clarification-issued-sms" | "clarification-reminder-email" | "clarification-reminder-sms" | "decision-email" | "decision-sms" | "notice-email" | "notice-sms" | "salary-stopped-email" | "salary-stopped-sms" | "salary-reinstated-email" | "salary-reinstated-sms" | "form-m-draft-ready-email" | "form-m-reminder-email" | "form-m-chase-email" | "form-m-receipt-email" | "access-request-acknowledged-email" | "access-request-notified-email" | "access-request-notified-sms" | "access-decision-applicant-email" | "access-decision-declarant-email" | "access-package-ready-email" | "access-officer-reminder-email" | "lea-grant-notice-email" | "lea-decision-email" | "certified-copy-ready-email";
        Recipient: {
            /** @constant */
            kind: "address";
            /** @description Email address or E.164 phone number, matching the channel */
            to: string;
        } | {
            /** @constant */
            kind: "person";
            /**
             * Format: uuid
             * @description Contacts resolved through the directory; failed with error no-contact when none
             */
            personId: string;
        };
        SendMessage: {
            channel: components["schemas"]["Channel"];
            recipient: components["schemas"]["Recipient"];
            template: components["schemas"]["TemplateId"];
            /** @description Validated against the template's parameter schema */
            params: {
                [key: string]: unknown;
            };
            /**
             * @default en
             * @enum {string}
             */
            locale: "en" | "sw";
            /** @description Tenant key for audit and per-tenant branding; optional for platform messages */
            tenant?: string;
        };
        /** @enum {string} */
        MessageStatus: "sent" | "failed";
        Message: {
            /** Format: uuid */
            id: string;
            channel: components["schemas"]["Channel"];
            template: components["schemas"]["TemplateId"];
            status: components["schemas"]["MessageStatus"];
            /** @description Reason when failed, e.g. timeout, rejected-recipient, no-contact */
            error?: string | null;
            providerMessageId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ProblemDetails: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            errors?: {
                path: string;
                message: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessage"];
            };
        };
        responses: {
            /** @description Message handed to the provider (or failed, see status) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Unknown template, invalid recipient or params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Caller lacks the messages scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
