# Generated by Django 6.1.1 on 2026-09-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryState',
            fields=[
                ('system', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('paused', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
