# Generated by Django 6.1.1 on 2026-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year_of_manufacture', models.PositiveSmallIntegerField()),
                ('owner_id_number', models.CharField(db_index=True, max_length=10)),
                ('registered_on', models.DateField()),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
    ]
