import { readFileSync, writeFileSync } from 'node:fs';

import type { Type } from '@nestjs/common';
import type { OpenAPIObject } from '@nestjs/swagger';
import { parse, stringify } from 'yaml';

import { type OpenApiOptions, scanOpenApiDocument } from './openapi.js';

type Components = NonNullable<OpenAPIObject['components']>;

/**
 * Operations and components drafted for specs not implemented yet (a partial OpenAPI document).
 * They may reference the implemented components, e.g. `#/components/schemas/Commission`.
 */
export interface Draft {
  paths?: OpenAPIObject['paths'];
  components?: Pick<Components, 'schemas' | 'parameters' | 'responses'>;
}

export interface ContractExportOptions extends OpenApiOptions {
  /**
   * The drafted operations: packages/schemas/drafts/<service>.yaml. Omit it when no later spec
   * drafts an operation of the service.
   */
  draftFile?: string;
  /** Where the contract goes: packages/schemas/internal/<service>.yaml, or a scratch file. */
  outputFile: string;
}

/**
 * Writes a service's contract: its OpenAPI document (controllers' decorators + Zod schemas,
 * scanned from `module` without starting it) plus the drafted operations of later specs, as
 * YAML in reading order. Each service's `contracts` script calls it; the drift check
 * (`pnpm contracts:drift`) runs that script with `--out <file>` and fails when the result
 * differs from the committed file, so the contract clients are generated from matches the code.
 */
export async function exportContract(module: Type, options: ContractExportOptions): Promise<void> {
  const { draftFile, outputFile, ...openApi } = options;
  const generated = await scanOpenApiDocument(module, openApi);
  const draft = draftFile === undefined ? {} : (parse(readFileSync(draftFile, 'utf8')) as Draft);
  const document = readable(withDraft(generated, draft));
  const header =
    draftFile === undefined
      ? `# Generated by \`pnpm --filter @adili/${openApi.name} contracts\` from the ${openApi.name} service: do not edit.
`
      : `# Generated by \`pnpm --filter @adili/${openApi.name} contracts\`: do not edit.
# Implemented operations come from the ${openApi.name} service; operations marked \`x-draft\` come
# from packages/schemas/drafts/${openApi.name}.yaml until they are implemented.
`;
  const yaml = stringify(document, {
    lineWidth: 0,
    aliasDuplicateObjects: false,
    singleQuote: true,
  });
  writeFileSync(outputFile, header + yaml);
}

const HTTP_METHODS = new Set(['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace']);

/**
 * The implemented document plus the draft, with every drafted operation marked `x-draft: true`.
 * A draft that names an implemented operation or component is an error: once something is
 * implemented, its draft must be deleted so that the code alone defines it.
 */
export function withDraft(implemented: OpenAPIObject, draft: Draft): OpenAPIObject {
  const conflicts: string[] = [];
  const paths = { ...implemented.paths };
  for (const [path, draftItem] of Object.entries(draft.paths ?? {})) {
    const implementedItem = paths[path];
    const item: Record<string, unknown> = { ...implementedItem };
    for (const [key, value] of Object.entries(draftItem)) {
      if (implementedItem && key in implementedItem) {
        conflicts.push(`paths.${path}.${key}`);
      } else if (implementedItem && !HTTP_METHODS.has(key)) {
        // Path-level fields would change the implemented operations too.
        conflicts.push(`paths.${path}.${key} (move it into the drafted operations)`);
      } else {
        item[key] = HTTP_METHODS.has(key) ? { ...value, 'x-draft': true } : value;
      }
    }
    paths[path] = item;
  }

  const components: Components = { ...implemented.components };
  for (const section of ['schemas', 'parameters', 'responses'] as const) {
    const drafted = draft.components?.[section];
    if (!drafted) continue;
    const merged: Record<string, unknown> = { ...components[section] };
    for (const [name, value] of Object.entries(drafted)) {
      if (name in merged) conflicts.push(`components.${section}.${name}`);
      merged[name] = value;
    }
    components[section] = merged as never;
  }

  if (conflicts.length > 0) {
    throw new Error(
      `The draft redefines what the service implements; delete these from the draft:\n  ${conflicts.join('\n  ')}`,
    );
  }
  return { ...implemented, paths, components };
}

const OPERATION_KEY_ORDER = [
  'tags',
  'summary',
  'description',
  'operationId',
  'x-draft',
  'parameters',
  'requestBody',
  'responses',
  'security',
];

/**
 * The document with keys in reading order (info before paths, an operation's summary before
 * its responses) and without empty lists, as people read the exported contract.
 */
function readable(document: OpenAPIObject): OpenAPIObject {
  const { openapi, info, servers, tags, paths, components, ...rest } = document;
  return {
    openapi,
    info,
    ...(servers?.length ? { servers } : {}),
    ...(tags?.length ? { tags } : {}),
    paths: Object.fromEntries(
      Object.entries(paths).map(([path, item]) => [
        path,
        Object.fromEntries(
          Object.entries(item).map(([key, value]) => [
            key,
            isOperation(value) ? orderOperation(value) : value,
          ]),
        ),
      ]),
    ),
    ...(components ? { components } : {}),
    ...rest,
  };
}

function isOperation(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && 'responses' in value;
}

function orderOperation(operation: Record<string, unknown>): Record<string, unknown> {
  const rank = (key: string) => {
    const index = OPERATION_KEY_ORDER.indexOf(key);
    return index === -1 ? OPERATION_KEY_ORDER.length : index;
  };
  return Object.fromEntries(
    Object.entries(operation)
      .filter(([key, value]) => !(key === 'parameters' && Array.isArray(value) && !value.length))
      .sort(([a], [b]) => rank(a) - rank(b)),
  );
}
