import { principalSchema } from '@adili/api-kit';
import type { z } from 'zod';

import { assignReportingOfficerBody } from './commissions/assign-reporting-officer.js';
import {
  commissionTypeSchema,
  createCommissionBody,
  officerCategoryCodeSchema,
  slugSchema,
} from './commissions/create-commission.js';
import {
  createTenantPolicyVersionBody,
  tenantPolicyHistorySchema,
  tenantPolicyVersionSchema,
} from './commissions/policy-representation.js';
import {
  commissionPageSchema,
  commissionSchema,
  internalCommissionListItemSchema,
  internalCommissionListSchema,
  internalCommissionSchema,
  internalCommissionStaffSchema,
  officerCategorySchema,
  reportingOfficerSchema,
  reportingOfficerStateSchema,
  rosterSummarySchema,
} from './commissions/representation.js';
import {
  agencyCodeSchema,
  agencySchema,
  internalLeaOfficerSchema,
  leaOfficerAccountSchema,
  leaOfficerStateSchema,
  provisionAgencyOfficerBody,
} from './law-enforcement/representation.js';
import {
  applicantOnboardingProblemSchema,
  applicantOnboardingSessionCreatedSchema,
  applicantOnboardingSessionSchema,
  applicantOnboardingStateSchema,
  identityDocumentKindSchema,
  identityStatusSchema,
  startApplicantOnboardingBody,
} from './onboarding/applicants/representation.js';
import { onboardingFailuresSchema } from './onboarding/failures/representation.js';
import {
  identifyDeclarantBody,
  maskedContactSchema,
  ofrSchema,
  onboardingCommissionSchema,
  onboardingConfirmResultSchema,
  onboardingOutcomeSchema,
  onboardingProblemSchema,
  onboardingSessionCreatedSchema,
  onboardingSessionSchema,
  onboardingStateSchema,
  otpChannelSchema,
  provideOnboardingContactBody,
  verifyOnboardingOtpBody,
} from './onboarding/representation.js';
import {
  applicantIdentityDocumentSchema,
  applicantProfileSchema,
  declarantProfileSchema,
  internalApplicantSchema,
  personContactsSchema,
  personNationalIdSchema,
  personSummarySchema,
  verifyApplicantIdentityBody,
} from './persons/representation.js';
import {
  confirmExitsBody,
  exitsResultSchema,
  keepResultSchema,
  keepRosterRecordsBody,
  recordRosterExitBody,
} from './roster/exits/representation.js';
import {
  columnMappingSchema,
  importChannelSchema,
  importCountsSchema,
  importConflictProblemSchema,
  importFailureCodeSchema,
  importStateSchema,
  previewRosterImportBody,
  rosterImportPageSchema,
  rosterImportPreviewSchema,
  rosterImportRowPageSchema,
  rosterImportRowSchema,
  rosterImportSchema,
  rosterBatchProblemSchema,
  rosterRowInputSchema,
  rowErrorSchema,
  startBatchImportBody,
  startFileImportBody,
  startRosterImportBody,
} from './roster/import/representation.js';
import {
  internalRosterRecordPageSchema,
  rosterNationalIdSchema,
  internalRosterRecordSchema,
  onboardingInvitationSchema,
  reportingEntityRefSchema,
  rosterRecordImportSchema,
  rosterRecordListItemSchema,
  rosterRecordPageSchema,
  rosterRecordSchema,
  rosterRecordStateSchema,
} from './roster/records/representation.js';
import {
  rosterApiCredentialSchema,
  rosterApiCredentialWithSecretSchema,
} from './roster/api-credential/representation.js';

/**
 * Named schemas of the directory's OpenAPI document (`#/components/schemas/<name>`), which is
 * exported to packages/schemas/internal/directory.yaml by `pnpm contracts`.
 */
export const OPENAPI_SCHEMAS: Record<string, z.ZodType> = {
  Principal: principalSchema,
  Slug: slugSchema,
  CommissionType: commissionTypeSchema,
  OfficerCategoryCode: officerCategoryCodeSchema,
  OfficerCategory: officerCategorySchema,
  CreateCommission: createCommissionBody,
  AssignReportingOfficer: assignReportingOfficerBody,
  ReportingOfficerState: reportingOfficerStateSchema,
  ReportingOfficer: reportingOfficerSchema,
  RosterSummary: rosterSummarySchema,
  Commission: commissionSchema,
  CommissionPage: commissionPageSchema,
  InternalCommission: internalCommissionSchema,
  InternalCommissionListItem: internalCommissionListItemSchema,
  InternalCommissionList: internalCommissionListSchema,
  InternalStaffList: internalCommissionStaffSchema,
  TenantPolicyVersion: tenantPolicyVersionSchema,
  TenantPolicyHistory: tenantPolicyHistorySchema,
  CreateTenantPolicyVersion: createTenantPolicyVersionBody,
  RosterApiCredential: rosterApiCredentialSchema,
  RosterApiCredentialWithSecret: rosterApiCredentialWithSecretSchema,
  ImportChannel: importChannelSchema,
  ImportState: importStateSchema,
  ImportFailureCode: importFailureCodeSchema,
  ColumnMapping: columnMappingSchema,
  ImportCounts: importCountsSchema,
  RosterImport: rosterImportSchema,
  StartFileImport: startFileImportBody,
  RosterRowInput: rosterRowInputSchema,
  StartBatchImport: startBatchImportBody,
  StartRosterImport: startRosterImportBody,
  RosterBatchProblem: rosterBatchProblemSchema,
  ImportConflictProblem: importConflictProblemSchema,
  PreviewRosterImport: previewRosterImportBody,
  RosterImportPreview: rosterImportPreviewSchema,
  RosterImportPage: rosterImportPageSchema,
  RowError: rowErrorSchema,
  RosterImportRow: rosterImportRowSchema,
  RosterImportRowPage: rosterImportRowPageSchema,
  RosterRecordState: rosterRecordStateSchema,
  ReportingEntityRef: reportingEntityRefSchema,
  RosterRecordListItem: rosterRecordListItemSchema,
  RosterRecordImport: rosterRecordImportSchema,
  RosterRecord: rosterRecordSchema,
  RosterRecordPage: rosterRecordPageSchema,
  InternalRosterRecord: internalRosterRecordSchema,
  OnboardingInvitation: onboardingInvitationSchema,
  InternalRosterRecordPage: internalRosterRecordPageSchema,
  RosterNationalId: rosterNationalIdSchema,
  ConfirmExits: confirmExitsBody,
  ExitsResult: exitsResultSchema,
  KeepRosterRecords: keepRosterRecordsBody,
  KeepResult: keepResultSchema,
  RecordRosterExit: recordRosterExitBody,
  Ofr: ofrSchema,
  OtpChannel: otpChannelSchema,
  OnboardingCommission: onboardingCommissionSchema,
  IdentifyDeclarant: identifyDeclarantBody,
  OnboardingState: onboardingStateSchema,
  MaskedContact: maskedContactSchema,
  OnboardingOutcome: onboardingOutcomeSchema,
  OnboardingSession: onboardingSessionSchema,
  OnboardingSessionCreated: onboardingSessionCreatedSchema,
  OnboardingConfirmResult: onboardingConfirmResultSchema,
  OnboardingProblem: onboardingProblemSchema,
  OnboardingFailures: onboardingFailuresSchema,
  DeclarantProfile: declarantProfileSchema,
  PersonSummary: personSummarySchema,
  PersonContacts: personContactsSchema,
  PersonNationalId: personNationalIdSchema,
  VerifyOnboardingOtp: verifyOnboardingOtpBody,
  ProvideOnboardingContact: provideOnboardingContactBody,
  AgencyCode: agencyCodeSchema,
  Agency: agencySchema,
  LeaOfficerState: leaOfficerStateSchema,
  LeaOfficerAccount: leaOfficerAccountSchema,
  InternalLeaOfficer: internalLeaOfficerSchema,
  ProvisionAgencyOfficer: provisionAgencyOfficerBody,
  IdentityDocumentKind: identityDocumentKindSchema,
  IdentityStatus: identityStatusSchema,
  StartApplicantOnboarding: startApplicantOnboardingBody,
  ApplicantOnboardingState: applicantOnboardingStateSchema,
  ApplicantOnboardingSession: applicantOnboardingSessionSchema,
  ApplicantOnboardingSessionCreated: applicantOnboardingSessionCreatedSchema,
  ApplicantOnboardingProblem: applicantOnboardingProblemSchema,
  ApplicantIdentityDocument: applicantIdentityDocumentSchema,
  ApplicantProfile: applicantProfileSchema,
  InternalApplicant: internalApplicantSchema,
  VerifyApplicantIdentity: verifyApplicantIdentityBody,
};
