# Generated by Django 6.1.1 on 2026-09-25 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('to', models.CharField(max_length=16)),
                ('sender_id', models.CharField(default='ADILI', max_length=11)),
                ('message', models.TextField(max_length=918)),
                ('status', models.CharField(choices=[('delivered', 'Delivered')], default='delivered', max_length=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
